### ISSUE TITLE
v3 schema-revision: copyright.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#100]
The `copyright.schema.json` will be used to define the copyright holder and year.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/copyright"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **holder** [expects: person.schema.json | organization.schema.json, count: 1]
- **year** [expects: year, count: 1]

**Comment by lzehl** [comment]
@jagru20 here the documentation of what needs to be implemented (connected to discussion in #76 ). Would you like to implement it or should I assign someone else?

**Comment by jagru20** [comment]
I think I can do this.

**Comment by lzehl** [comment]
thanks :slightly_smiling_face:
