### ISSUE TITLE
v3 schema-revision: digitalIdentifier.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#103]
The `digitalIdentifier.schema.json` will be used to define the digital identifier and it's type (scheme).

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/digitalIdentifier"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **identifier** [expects: free text, count: 1]
- **identifierScheme** [expects: identifierScheme.schema.json, count: 1]

**Comment by lzehl** [comment]
@olinux you think that's sufficient?

**Comment by olinux** [comment]
if the "identifierScheme" means the "type" (ORCID, Github, ...) then, yes :)

**Comment by lzehl** [comment]
@olinux yes! sorry I forgot to add the identifierScheme.schema.json, I'm doing it soon. It would/could include:
- type (controlledTerm, e.g. "ORCID", "ROR",  "DOI", "ISBN"+ ?) [required]
- schemeURI (iri, e.g. `"https://orcid.org/"`, `"https://ror.org/"`, `"https://www.doi.org/"`)  [optional?]
- identifierPattern (regex?) [optional?]

Happy to get feedback on this.
