### ISSUE TITLE
Check that all schema have a title tag

### ISSUE THREAD

**Issue by skoehnen** [openMetadataInitiative/openMINDS_core#114]
According to json-schema "title" and "description" are both keywords of a json-schema object and MUST be a string. Both of these keywords can be used to decorate a user interface with information about the data produced by this user interface. A title will preferably be short, whereas a description will provide explanation about the purpose of the instance described by this schema. We forgot the "title" in most schemas. This should be just the label used for this schema.

- [ ] softwareVersion.schema.json
- [ ] researchProduct.schema.json
- [ ] project.schema.json
- [ ] person.schema.json
- [ ] funding.schema.json
- [ ] datasetVersion.schema.json
- [ ] controlledTerm.schema.json

**Comment by skoehnen** [comment]
- [ ] softwareVersion.schema.json
- [ ] researchProduct.schema.json
- [ ] project.schema.json
- [ ] person.schema.json
- [ ] funding.schema.json
- [ ] datasetVersion.schema.json
- [ ] controlledTerm.schema.json

**Comment by lzehl** [comment]
@skoehnen & @UlrikeS91 this came up in #128 : should the title be
1) the label used in the schema filename (e.g. "softwareFeature")
2) or a display label (non-capitalized) (e.g. "software feature")?

**Comment by UlrikeS91** [comment]
Is this a question of what I would prefer? If so, I like option 2 better (e.g. "software feature"). If not, I don't know the answer ;)

**Comment by lzehl** [comment]
obsolete with #138 (title is not longer used)
