### ISSUE TITLE
v3 schema-revision: hash.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#116]
The `hash.schema.json` will be used to state the hash (digest and algorithm).

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/hash"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **digest** [expects: free text, count: 1]
- **algorithm** [expects: free text, count: 1]

**Comment by lzehl** [comment]
@skoehnen I've used hash.schema.json before but maybe hashCode is more precise?

**Comment by apdavison** [comment]
@lzehl it's usually just called a hash or digest. I've never seen "hash code" used. 

If you want a more descriptive name, I suggest "contentHash"

**Comment by lzehl** [comment]
@apdavison okay! hash it is :)

**Comment by olinux** [comment]
wouldn't you want algorithm to be a controlled term?

**Comment by lzehl** [comment]
@skoehnen or @apdavison you think it is feasible to make the algorithm a controlled term? I have no idea how many there are...
