### ISSUE TITLE
v3 schema-revision: studyTarget.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#118]
The `studyTarget.schema.json` will be used to emphasize the thing of interest (target) within a study.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/studyTarget"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **thingOfInterest** [expects: free text | controlledTerm.schema.json, count: 1]
- **type** [expects: controlledTerm.schema.json, count: 1]

Note for controlledTerm.schema.json for...
- **type** (`studyTargetType`): expects JSON-LDs for `species`, `disease`, `cell`, + ?

**Comment by lzehl** [comment]
@olinux is it possible in KG v3 to point to either a free text or a schema?  
Use case here: 
- if my study target ("homo sapiens") belongs to `species` a controlledTerm is already registered
- if my study target ("highly specific disease") belongs to `disease` a controlledTerm might not yet exist

Alternative: `thingOfInterest` always points to a controlledTerm. For undefined controlledTerms only the name is given in the schema.

**Comment by olinux** [comment]
>  is it possible in KG v3 to point to either a free text or a schema?

No, we don't have something like this - also because it would be rather difficult for clients to interpret since it couldn't e.g. be filtered by a type. 
One thing we should discuss is, if "controlledTerm" is the appropriate label for the schema since it includes some directives how to handle the access control. If we would just call it "term" (or something else), we could properly separate them in the implementation. structure-wise, it would look the same though.

**Comment by olinux** [comment]
I thought about this: We can have study targets allowed in two spaces - the controlledTerms and another one. While the "controlledTerm" study targets are more strict, we can let users define study targets more freely in the other space. They would be clearly separated and could be easily discriminated in terms of quality.

**Comment by lzehl** [comment]
@olinux sounds like a solution. Aim of the less defined space would be to keep it to a minimum, meaning going over those frequently to see if they can be migrated to controlled terms. What do you think?
