### ISSUE TITLE
v3 schema-revision: softwareFeature.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#119]
The `softwareFeature.schema.json` will contain metadata on the software feature.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/softwareFeature"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **definition**: [expects: string (format: iri, count: 0 - 1] 
- **description**: [expects: free text, count: 1] 
- **category**: [expects: controlledTerm.schema.json, count: 0 - 1] 
- **name** [expects: free text, count: 1]

Note for controlledTerm.schema.json for...
- **category** (`softwareFeatureCategory`): expects JSON-LDs for (cf. uniMINDS entries?)

**Comment by lzehl** [comment]
@jagru20 could you take this over and also see if something is missing / misunderstood in the documentation?

**Comment by jagru20** [comment]
yes, do you assign me?
