### ISSUE TITLE
v3 schema-revision: subject.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#120]
The `subject.schema.json` will be used to provide information on the subject that was studied.
Note: should be implemented in folder "specimen".

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/subject"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **biologicalSex** [expects: controlledTerm.schema.json, count: 1]
- **identifier** [expects: free text, count: 1]
- **genotype** [expects: controlledTerm.schema.json, count: 0 - 1]
- **phenotype** [expects: controlledTerm.schema.json, count: 0 - 1]
- **quantity** [expects: number, count: 1]
- **species** [expects: controlledTerm.schema.json, count: 1]
- **strain** [expects: controlledTerm.schema.json, count: 0 - 1]
- **studiedStates** [expects: subjectState.schema.json, count: 1 - N]

Note for controlledTerm.schema.json for...
- **biologicalSex** (`biologicalSex`): expects JSON-LDs for `male`, `female`, `hermaphrodite`, `unknown`
- **genotype** (`genotype`): expects JSON-LDs for (cf. MINDS entries?)
- **phenotype** (`phenotype`): expects JSON-LDs for (cf. MINDS entries?)
- **species** (`species`): expects JSON-LDs for (cf. MINDS entries)
- **strain** (`strain`): expects JSON-LDs for (cf. MINDS entries?)

**Comment by olinux** [comment]
Is "strain" really a species or its own controlled term?

**Comment by lzehl** [comment]
that's a copy paste error. should be **strain** (`strain`). I've corrected it
