### ISSUE TITLE
v3 schema-revision: subjectState.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#121]
The `subjectState.schema.json` will be used to provide information on the state the subject was in when it was studied.
Note: should be implemented in folder "specimen".

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/subjectState"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **age** [expects: quantitativeValue.schema.json, count: 0 - 1]
- **ageCategory** [expects: controlledTerm.schema.json, count: 1]
- **bodyWeight** [expects: quantitativeValue.schema.json, count: 0 - 1]
- **disease** [expects: controlledTerm.schema.json, count: 0 - 1]
- **functionalImpairments** [expects: free text, count: 0 - 1]

Note for controlledTerm.schema.json for...
- **ageCategory** (`ageCategory`): expects JSON-LDs for `adult`, `juvenile`, etc
- **disease** (`disease`): expects JSON-LDs for e.g., `epilepsy`, etc.

**Comment by lzehl** [comment]
- `disease` could maybe be also name `pathology` (as in tissueSampleState #123 )

**Comment by olinux** [comment]
I assume ageCategory should be its own controlled term

**Comment by lzehl** [comment]
yes! again copy/paste error. I've corrected it in the docu above
