### ISSUE TITLE
v3 schema-revision: parameterSetting.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#126]
The `parameterSetting.schema.json` will be used to provide more detail for a user-defined parameter used in the individually executed techniques and tasks.
Note: should be implemented in folder "experiment". This schema can be used to immediately register important user-provided information without going directly into the in-depth metadata descriptions.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/protocolExecution"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **description** [expects: free text, count: 1]
- **key** [expects: free text, count: 1]
- **value** [expects: string | quantitativeValue.schema.json, count: 1]
- **relevantParameterFor** [expects: controlledTerm.schema.json, count: 0 - 1]

Note for controlledTerm.schema.json for...
- **relevantParameterFor** (`behavioralTasks` | `techniques`): expects JSON-LDs for e.g., `ARCHI standard`, `resting state` etc. (cf. MINDS after cleanup) or `functional magnetic resonance imaging`, etc. (cf. MINDS after cleanup)

**Comment by olinux** [comment]
shouldn't the "valueUnit" be a controlled term (unit) - the same as used for the quantitative value?

**Comment by lzehl** [comment]
yes... don't know how that error happend :see_no_evil: I've corrected the docu above

**Comment by lzehl** [comment]
for values that do not have a unit we need to have a "none" for the unit in the quantitative value schema

**Comment by lzehl** [comment]
Another thing: I would like to make an additional relation here between ParameterSettings.
Use Case: I define an anaesthesia agent in one parameterSetting and how much was used of this agent in another parameterSetting.

**Comment by lzehl** [comment]
AHHH NOOO! :see_no_evil: I remember now why value and unit need to be kept separate here:
value does not mean number! It could be a string

As for the case mentioned above:
key: anaesthetic agent
value: isoflurane
unit: - 
relevantParameterFor: anaesthesiaTechnique.schema.json (controlledTerm/Technique)
validFor: - 

The second one would be:
key: flow rate
value: 75
unit: %
relevantParameterFor: anaesthesiaTechnique.schema.json (controlledTerm/Technique)
validFor: isoflurane.schema.json (parameterSetting)

Note: any other suggestion for "validFor" are welcome
