### ISSUE TITLE
v3 schema organization

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#127]
I would like to meaningful organize the schemas within openMINDS v3.0.
Suggested structure (last update Oct 27):

**products/**
    ~`contribution.schema.json`~ (moved to miscellaneous)
    ~`copyright.schema.json`~ (moved to miscellaneous)
    `datasetVersion.schema.json`
    ~`digitalIdentifier.schema.json`~ (copy/paste error; was moved to miscellaneous)
    ~`funding.schema.json`~ (moved to miscellaneous)
    ~`license.schema.json`~ (moved to miscellaneous)
    `metadataConstructVersion.schema.json`
    `modelVersion.schema.json`
    `project.schema.json`
    `researchProduct.schema.json`
    `softwareFeature.schema.json`
    `softwareVersion.schema.json`

**data/**
    `fileBundle.schema.json`
    `fileInstance.schema.json`
    `fileRepository.schema.json`
    `hash.schema.json`
    `mediatype.schema.json`

**experiment/**
    `parameterSetting.schema.json`
    `protocol.schema.json`
    `protocolExecution.schema.json`
    `studyTarget.schema.json`

**specimen/**
    `subject.schema.json`
    `subjectState.schema.json`
    `tissueSample.schema.json`
    `tissueSampleState.schema.json`

**miscellaneous/**
    `contribution.schema.json`
    ~`controlledTerm.schema.json`~ (moved to controlledTerms; based on discussion with Oli)
    `copyright.schema.json`
    `digitalIdentifier.schema.json`
    `funding.schema.json`
    `license.schema.json`
    `organization.schema.json`
    `person.schema.json`
    `resource.schema.json`

**controlledTerms/**
    `controlledTerm.schema.json`
    `<<TERM-TYPE>>.schema.json` (e.g., biologicalSex.schema.json)

**Comment by lzehl** [comment]
@UlrikeS91 @apdavison @bweyers @olinux @skoehnen it would be great to hear your opinion on this.

@olinux let me know if the substructure somehow should be more useful for the KG team (e.g. for handling the different KG spaces) and needs adaptions for this purpose

**Comment by UlrikeS91** [comment]
Overall, agreed. The folders seem reasonable to me. Just a few things I'm unsure about:

1. `digitalIdentifier` is listed twice. Pretty sure you only want to have it under miscellaneous/ and not under products/. If you intended to have it under products/, I would disagree ;) 
2. I'm struggeling a bit with `contribution`, `license` and `funding` as part of product/. To me, these aren't products. Maybe we could move those to miscellaneous/? 
3. `copyright` makes sense in product/, but I still don't like it. Compared to the other products, this just doesn't seem to fit as well as the rest. If none else has this feeling, then it should just stay in product/.

**Comment by apdavison** [comment]
I agree with @UlrikeS91: I would put `copyright`, `contribution`, `license`, `funding` under miscellaneous

**Comment by bweyers** [comment]
@lzehl As far as I can see, that makes a lot of sense. However, I do not like the miscellaneous section but also do not have a good proposal how to "fix" this. But as we move more under his category, it is fine with me!

**Comment by olinux** [comment]
@lzehl Just go ahead - the organization in different spaces is specific to EBRAINS and reflects how we want to organize the permissions. Don't let yourself be influenced by this for the generic schemas.

**Comment by lzehl** [comment]
@apdavison @bweyers @UlrikeS91 @olinux Thank you all for the quick feedback. I agree with you (see adopted documentation above)

**Comment by lzehl** [comment]
solved in PR #132
