### ISSUE TITLE
Rename version folders in al repos

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#141]
As discussed during meeting, we will rename all version folders in all repos from "vX.0" to "vX".

For example: `https://github.com/HumanBrainProject/openMINDS_core/tree/master/v3.0` change to `https://github.com/HumanBrainProject/openMINDS_core/tree/master/v3`.

**Comment by skoehnen** [comment]
Did it, and now we are discussing it again 😅

**Comment by lzehl** [comment]
I'm closing this. Obsolete (moved versions to branches)
