### ISSUE TITLE
"associatedFileExtension" should not be required in schemas/data/contentType.schema.tpl.json

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#149]
Some content types are based on directories, not files, so don't have an associated extension

**Comment by lzehl** [comment]
@apdavison thanks for reporting this issue. I agree, the associated file extensions cannot be required for directories. I'll update this asap.

**Comment by lzehl** [comment]
Solved in latest commit on v3 (as exception I did not make a PR for this small change)
