### ISSUE TITLE
What property to use for schema "contentType"? 

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#152]
I've went trough all schemas again and got confused when I came across the schema for `fileRepository`. One of the properties is `format` with count 0 - 1, which confused me. I associated `format` with file format rather than the actual meaning, which is e.g. to give repository structures such as BIDS. This also explains the coutn of 0 - 1 (which would be weird for file formats since a repository can have files with more than one file format).
So, @lzehl and I talked briefly about it and think we should consider again which properties to use when referring to the schema for `contentType`. I looked up all the places `contentType` was referenced and the property used:  

metaDataModelVersion --> serializationFormat 
metaDataModelVersion --> specificationFormat 
modelVersion --> format 
softwareVersion --> inputFormat 
softwareVersion --> outputFormat 
fileRepository --> format 
fileBundle --> format 
fileInstance --> format 

If I am not mistaken, in most cases the association of `format` with file format actually makes sense except for `fileRepository` and `fileBundle`. 
Maybe we could find another property name for `fileRepository` and `fileBundle`? 

@apdavison, @bweyers and @lzehl, what do you think?  

@lzehl, did I forget to mention any other questions related to this?

**Comment by lzehl** [comment]
@UlrikeS91 no I think you covered all aspects.

@apdavison & @bweyers : here some options I can think of at the moment:
1. "dataModel"
2. "dataModelFormat"
3. "usedDataStructure"
4. "fileRepositoryFormat" | "fileBundleFormat"

What do your think? Of course feel free to make a counter suggestion as well.

**Comment by apdavison** [comment]
I don't think this is a problem. We can just keep "format". in @UlrikeS91's example, the contentType of the `fileRepository` or `fileBundle` would be something like `vnd.bids`. Each of the individual files within the repository or bundle can have its own contentType (`application/json`, for example).

**Comment by lzehl** [comment]
@apdavison : I agree, but we need to be clear in the instructions then. People that are unfamiliar with the concept of data structure formats (such as bids) might assume that "format" should state the formats of the files within that repository/bundle.

Do you have a nice suggestion for such an instruction?

**Comment by apdavison** [comment]
How about "leave blank if this bundle represents just a folder; if the files within the bundle are part of a single entity, such as a BIDS dataset, use the appropriate contentType" ?

**Comment by lzehl** [comment]
Thanks. That helps :) I will maybe switch it around a bit. "single entity" is a bit difficult to understand, maybe 
"If files within the bundle are organized and formatted according to a formal data structure use the appropriate contentType. Leave blank otherwise."
