### ISSUE TITLE
Is identifier pattern meant to be a regex?

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_core#156]
What was the idea for the values of the identifier pattern? Is it a regex?

https://github.com/HumanBrainProject/openMINDS_core/blob/850b6a03c9726ea5ce7d03854d446f46e03fcdd1/schemas/miscellaneous/digitalIdentifierSchema.schema.tpl.json#L16

**Comment by lzehl** [comment]
Yes. I think that should be a regex. The description / instruction should be updated accordingly. We should also state what regex is used (I suggest the same as for json-schema. Draft 7 is using the ECMA 262 dialect.)

@olinux what do you think?
