### ISSUE TITLE
Add affiliations to link Person and Organization

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#158]
In the context of Live Papers, I would like to be able to provide affiliations for the authors. The LivePaper schema should probably be in an openMINDS extension, but I think the concept of affiliation is sufficiently generic to belong in core.

Specifically, I propose to add an Affiliation schema in core/actors, which would link one Person with one Organization, and would have a start date and end date as optional additional fields.

**Comment by lzehl** [comment]
I agree that affiliations should be covered in the core (we had it on the list and then forgot about it again...). 
Do we need to be able to hide them like the emails? 

TODO then: add a property called "affiliation" to Person schema that links to an Affiliation schema. 
Adding an Affiliation schema to ACTORS with properties "startDate" (type: string, format: date), "endDate" (type: string, format: date) and "organization" (type: object, link to Organization schema).

@apdavison Do you agree? Could you take care of the PR or should I?

**Comment by apdavison** [comment]
@lzehl I'll make a PR, it will be good practice for getting to grips with the schema templates

**Comment by lzehl** [comment]
great :slightly_smiling_face: let me know if you have questions. I still need to do a proper documentation for the template dialect.

**Comment by lzehl** [comment]
This issue was solved in the PR #162. I'll close it now.
