### ISSUE TITLE
Changing / Extending ParameterSetting

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#161]
This issue is made for documentation purposes and to incorporate more feedback (if necessary).
It was discussed with @UlrikeS91 and @olinux offline in advance.

**Summary of the offline discussion:**

First, the current ParameterSetting schema is meant to only hold one parameter setting. Discussing more use cases / examples this turns out to be not sufficient in case of parameter settings that are strongly related (e.g., `"anestheticAgent": "Isoflurane"` and `"concentration": "0.5%"` (the latter of course as QuantitativeValue)). 

This could be handled either by introducing a "isRelatedTo" in the ParameterSetting schema (which may lead quickly to rather complex structures) or by grouping parameter settings. 

Second, the properties of the parameter settings are misleading at the moment. A change of the properties should be considered.

And third, would it not be smart to enter a QuantitativeValue for numeric parameters? Allowing an entry to be an object OR a string seems to be technically difficult. Therefore this part cannot be implemented. 

**Summary of suggested solution:**

Two schemas: ParameterSettings schema which is grouping (embedded) Parameter schema.

**`ParameterSettings.schema.tpl.json` properties:**
+ "parameters" (type: object (as embeddedTypes), link to Parameter.schema.tpl.json, count: 1-n)
+ "relevantFor" (type: object, link to BehavioralTask OR Technique, count: 1)

**`Parameter.schema.tpl.json` properties:**
+ "parameterName" (type: string, free text)
+ "parameterEntry" (type: string OR number)
+ "unitOfMeasurement" (type: object, link to UnitOfMeasurement)
+ "description" (type: string, free text)

@apdavison , @UlrikeS91 , @olinux would that work? what do you think?

@apdavison would that collide with the in-depth schemas?

**Comment by apdavison** [comment]
@lzehl yes, I think this is going too far with core, and should be left to openMINDS extensions for in-depth metadata.

At the Tier 1 level, I would solve the anaesthetic agent example by putting `"anestheticAgent": "isoflurane 0.5%"`.

For going beyond this, we could imagine an openMINDS/chemistry extension - see [helmholtz/chemistry](https://github.com/apdavison/helmholtz/blob/master/helmholtz/chemistry/models.py) and [helmholtz/drugs](https://github.com/apdavison/helmholtz/blob/master/helmholtz/drugs/models.py) for how we did this in Helmholtz (which was a pre-HBP attempt to develop something similar to the KG, using Django). In the more general case, we have _solutions_, which contain multiple _substances_ in specific quantities, with _chemical products_ obtained from specific manufacturers. This is often important information for patch clamp recording and other _in vitro_ experiments.

For examples outside chemicals I would proceed in a similar manner, combining related parameters into single strings for core/Tier 1, and then decomposing them using extensions.

[The principles of articulation between core and in-depth metadata is something I'd like to discuss in detail soon, maybe in the monthly meetings; I've already had a preliminary informal discussion with @olinux]

**Comment by lzehl** [comment]
@apdavison I don't see how combining would make the issue much simpler, but maybe I did not fully understand. To have all parameters to one technique grouped directly would still require a two schema setting, correct? But within that schema setting we could leave out the "unitOfMeasurement" and go with the combined string (and corresponding instructions on how to write this). Would it be useful to still have an explanation (description) from the user for the term he/she entered?

I'm only concerned for use cases where for one entity (e.g. agent) two different quantitative values would need to be provided.. But even then we could break it down to a string, e.g. (ignore that this might be a stupid example),  
`"anestheticAgent": "isoflurane (concentration: 0.5%; durationOfAdministration: 10 min)"`

What do you think? (also @UlrikeS91 , @skoehnen , @olinux , @jagru20, @Peyman-N )

**Comment by apdavison** [comment]
@lzehl I'm not sure I understand your point. Could you or @olinux explain why "Allowing an entry to be an object OR a string seems to be technically difficult"? - that seems to be the crux of this issue.

**Comment by lzehl** [comment]
@apdavison in principle there are three parts in this issue (sorry for not making that clearer in the issue):

1) grouping parameters that belong to the same technique  / behavioral task instead of entering them independently each with a reference to the same technique / task.
2) how to deal best with parameters that highly depend on each other / are highly related to each other and may lead to ambiguity (e.g., "used tracer":  ["tracer A", "tracer B"], "used tracer concentration" ["x %dose/g", "y  %dose/g"]; problem: what belongs to what?)
3) how to deal with the fact that we do not know if the parameter value is a quantitativeValue (meaning a number that needs a unit defined) or a string. @olinux could you please explain why it is problematic to allow property type to be  ["string", "object"]? Was it not possible according to JSON-schema or was it an issue within the KG?

Point 2 & 3 would be solvable by your suggestion to define the parameter values always to be strings and allowing combined values within that string (provided in a certain format which needs to be checked by curators).

Point 1 would be solvable by providing a schema that groups those parameters (as summarized in a previous comment).

**Comment by olinux** [comment]
@apdavison and @lzehl. The problem with having a property defined as a choice of ["string", "object"] is at the interpretation level (obviously, this is possible with JSON(-LD) and supposedly covered by JSON-Schema / SHACL): Any client would have to write conditions to handle this data - whilst having only objects would allow to specify type-filters on the query level (e.g. "I'm only interested in QuantitativeValues with unit X/parameter name y). So the complexity of the multi-type content can be solved already on this level. 

Although theoretically possible, an extension of the query mechanism to do similar filters on the "property type level" seems to be rather complex especially because the structure of the resulting payload becomes conditional. 

An additional challenge we would face is obviously the one for the KG Editor on how to visualize the input for this kind of dynamic result structure. Not impossible of course but tricky.

Because of this, it might simplify our and the clients life a lot when deciding for one or the other solution (either by using a primitive or an embedded object)

**Comment by lzehl** [comment]
@apdavison , @olinux , @UlrikeS91 

Because the ParameterSettings are supposed to be completely user defined, I wanted to make the following suggestion:
Could we ask for a string of format dictionary?
**ParameterSetting.schema.tpl.json**
+ "isValidFor" (object; count:1; link to controlledTerm/Technique OR controlledTerm/BehavioralTask)
+ "usedParameters" (string, format: dict; count:1)

I know that his solution requires more input/validation from the curators, and we would maybe need to provide people with templates (if they do not know what a dictionary is), but it may solve the issue that we just don't know what users would like to detail before Tier3 is fully in place for their dataset.

I also know that this format is not supported by json-schema, but would have to be supported by the generator instead for validation. But I think that could be solved, @olinux  correct?

What do you think?

**Comment by apdavison** [comment]
Would it work to define "StringParameter" (name + value) and "NumericalParameter" (name + QuantitativeValue), and have parameterSetting be an array that can contain (embedded) objects of both types?

**Comment by lzehl** [comment]
Sure ! I think that's a great idea. Relation of Parameters should be defined via the Name, then? E.g. 
StringParameter 1:
name: "retrogradeTracerA"
value: "X"
StringParameter 2:
name: "retrogradeTracerB"
value: "Y"
NumericalParameter 1:
name: "concentrationTracerA"
value: {->quantitativeValue X}
NumericalParameter 2:
name: "concentrationTracerB"
value: {->quantitativeValue Y}

**Comment by UlrikeS91** [comment]
Alternatively, @lzehl and I discussed this:

protocolExecution get parameterSetting as _embeddedType (array is allowed) and parameterSetting would have the following properties:  

**ParameterSetting**
properties:
- context (1 - 1)
- relevantFor (1 - 1): 
   "_linkedTypes": controlledTerms/technique OR controlledTerms/behaviouralTask
- setting (1 - N): 
    "_embeddedType": core/stringParameter OR core/numericalParameter


**For example (simplified):**

ProtocolExecution(tracerInjection):

--> ParameterSetting(BDA)
context: "BDA injection" 
relevantFor: --> "anterograde tracing"
setting:
---> stringParameter1: 
name: "anterograde tracer"
value: "BDA"
--> numericalParameter1: 
name: "concentration"
value: --> 2% 
--> numericalParameter2: 
name: "injection speed"
value: --> 2 nL/sec

--> ParameterSetting(PHAL)
context: "PHAL injection" 
relevantFor: --> "anterograde tracing"
setting:
---> stringParameter1: 
name: "anterograde tracer"
value: "PHAL"
--> numericalParameter1: 
name: "concentration"
value: --> 1% 
--> numericalParameter2: 
name: "injection speed"
value: --> 3 nL/sec

@apdavison and @olinux what do you think?
