### ISSUE TITLE
Allow more than one entry for license

### ISSUE THREAD

**Issue by jagru20** [openMetadataInitiative/openMINDS_core#164]
https://github.com/HumanBrainProject/openMINDS_core/blob/0e2cb6236b96d5c243a24675b69ed9304f4bbd95/schemas/products/researchProductVersion.schema.tpl.json#L103

While it is logical, that a dataset can only be published under one license at a time, software can be under more than one license. Therefore, after a quick discussion with @olinux we suggest allowing an array for license.

**Comment by xgui3783** [comment]
Cosign +1

**Comment by lzehl** [comment]
@jagru20 , @olinux , @xgui3783 thanks for that note. I guess the "license" property should be moved then to the specific research product to allow validation for different counts (or should we leave it to the curators to make sure)? I'm not even sure if in principle a dataset could also have multiple licenses...

@apdavison what about models?

**Comment by lzehl** [comment]
@jagru20 , @xgui3783 , @olinux out of curiosity: how does that work for software? are the licenses there attached rather to files than to software product as whole? Or can multiple license apply to the same file?

**Comment by jagru20** [comment]
As far as I know, the software as a whole can be distributed under more than one license. For example if a developer wants to make the software open source (e.g., under GPL) but also wants to profit from selling proprietary licenses to companies which include it into their business, for example. (This example is taken from [here](https://en.wikipedia.org/wiki/Multi-licensing))

**Comment by jagru20** [comment]
> 
> 
> @jagru20 , @olinux , @xgui3783 thanks for that note. I guess the "license" property should be moved then to the specific research product to allow validation for different counts (or should we leave it to the curators to make sure)? I'm not even sure if in principle a dataset could also have multiple licenses...
> 
> @apdavison what about models?

I think @UlrikeS91 described the procedure for more than one license per dataset [here](https://github.com/HumanBrainProject/openMINDS_core/issues/74#issuecomment-709055601) I suppose, this is still up to date? But I think this procedure is not directly applicable to software, because besides from the example in my above comment, where the two licenses are used for different cases, there is also the possibility that one or more licenses are combined to supplement each other for one piece of software.

**Comment by xgui3783** [comment]
hmm, it seems as far as software is concerned, it can get quickly complicated. 

In addition to @jagru20 , some software packages allow users to choose:

https://www.npmjs.com/package/path-is-inside

some software packages specifies that both license apply:

https://www.npmjs.com/package/sha.js

**Comment by UlrikeS91** [comment]
> I think @UlrikeS91 described the procedure for more than one license per dataset [here](https://github.com/HumanBrainProject/openMINDS_core/issues/74#issuecomment-709055601) I suppose, this is still up to date? But I think this procedure is not directly applicable to software, because besides from the example in my above comment, where the two licenses are used for different cases, there is also the possibility that one or more licenses are combined to supplement each other for one piece of software.

This is how we have viewed this so far, yes. In 99% of the cases, I assume that this will still be valid. Based on this Wikipedia link @jagru20 pasted into his comment, this whole things seems to be very challenging...

"When software is multi-licensed, recipients can typically choose the terms under which they want to use or distribute the software, but the simple presence of multiple licenses in a software package or library does not necessarily indicate that the recipient can freely choose one or the other. In some cases, especially when the software has multiple origins, all the accompanied licenses apply at the same time. The applicability of the different licenses has to be individually checked. The distributor may or may not apply a fee to either option."

It seems to me, that we may need to consider an additional field related to the licenses which indicates the users options (choose freely, all apply, etc.).

Generally, if we don't want to all this for all `researchProducts`, we need to do what @lzehl suggested and move the property to the individual research products. 
Out of curiosity, can anybody come up with a case where we may want to all several licenses for datasets too? Being able to combine different licenses could be useful for datasets.

**Comment by lzehl** [comment]
I discussed this issue with @olinux and we decided for the following option:

The property "license" will be moved to the specific research product version allowing for multiple licenses for model and software versions, and only one license (for now) for dataset versions. 

@jagru20 do you have the time to take this over, or should I do the PR on this?

**Comment by jagru20** [comment]
To be honest, I would be very thankful if you could do this.

**Comment by lzehl** [comment]
@jagru20 sure! I'll take care of it :)
