### ISSUE TITLE
otherContributions embedded?

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_core#169]
I would like to suggest to make the "otherContributors" an embedded type instead. This is because:
- A contribution can not exist without its product
- The "https://openminds.ebrains.eu/core/Contribution" is a minimal schema (very few properties) and therefore well suited for being embedded

https://github.com/HumanBrainProject/openMINDS_core/blob/802161ff8ac0ece09487a090ffb1dc15fc617a9f/schemas/products/researchProductVersion.schema.tpl.json#L114

**Comment by lzehl** [comment]
This is then an embedded schema with links to not embedded schemas, correct? But in principle, quantitativeValue is this as well (linking to controlledTerm/UnitOfMeasurement). 

@olinux it makes sense to me. Should I do the PR? Or should I make the commit in PR #168?

**Comment by lzehl** [comment]
@olinux this request is now integrated as commit to PR #168

**Comment by lzehl** [comment]
This issue was solved in PR #168
