### ISSUE TITLE
License update

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#180]
Remove `"deed"` and add `"webpage"`.

Deed and legal code are too similar and it's unnecessary to have both. We discussed to have a link to a webpage instead to read up on things around the legal code instead. 

Webpage is an array so that e.g. both the homepage for the license(s) can be linked plus something else (spdx.org or similar).

**Comment by UlrikeS91** [comment]
done in #184

**Comment by lzehl** [comment]
@UlrikeS91 thank you!
