### ISSUE TITLE
Hash to be embedded type

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_core#187]
I would suggest to make the hash an embedded type since it's very clear that this inherits the life-cycle of its parent (no matter if filebundle, filerepository or fileinstance)

https://github.com/HumanBrainProject/openMINDS_core/blob/9e52a10cc343cfae9468b0b6cf1fce08785975c6/schemas/data/fileBundle.schema.tpl.json#L25

https://github.com/HumanBrainProject/openMINDS_core/blob/9e52a10cc343cfae9468b0b6cf1fce08785975c6/schemas/data/fileRepository.schema.tpl.json#L15

https://github.com/HumanBrainProject/openMINDS_core/blob/9e52a10cc343cfae9468b0b6cf1fce08785975c6/schemas/data/fileInstance.schema.tpl.json#L19

**Comment by lzehl** [comment]
@olinux Yes, I agree. I'll update it.

**Comment by lzehl** [comment]
@olinux PR #188  is ready for review :wink:
