### ISSUE TITLE
Could we introduce a QuantitativeValueArray schema?

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#189]
The suggestion to introduce a QuantitativeValueArray schema came up in the PR #177, but a decision was postponed to the next openMINDS revision.

A QuantitativeValueArray schema could be useful for simplifying the definition of larger numerical arrays (with no size limitation) where all values have the same unit. 

The tricky think about this is the definition of the uncertainties of the value array which can either be a pair of numbers defining the same uncertainty for all values in the array, or an array of tuples with the same length as the array of values. 

An array of tuples within JSON-Schema is defined the following way (I think):
```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "exampleArrayOfTuples": {
      "type": "array",
      "items": {
      	"type": "array",
        "items": {
          "type": "number"
        },
        "minItems": 2,
        "maxItems": 2
      }
    },
    "exampleArrayOf2Numbers": {
      "type": "array",
      "items": {
      	"type": "number"
      },
      "minItems": 2,
      "maxItems": 2
    }
  }
}
```
In principle the "oneOf" keyword should allow the combination of both, but I'm unsure how to solve the different requirements of the array size for the two different items types (when combined).

Any ideas/suggestions?

**Comment by lzehl** [comment]
@apdavison & @Peyman-N I think I need in particular your feedback for this one. Could you comment/make suggestions?

**Comment by UlrikeS91** [comment]
Let's revive this issue. @lzehl, I looked into tuple validation and it seems that the easiest option would be to use `prefixItems`. If I'm not mistaken, this predetermines an order within an array. 

The example @lzehl gave in the PR #117 was this (numericalParameter with an array of quantitative values): 
"name": "stimulusTriggerPoints",
"value": [1s, 2s, 4s]

Our `quantitativeValue` schema has: 
```
value | 1-1 | number
uncertainty | 0 or 2 | number
typeOfuncertainty | 0 - 1 | controlledTerms/TypeOfUncertainty
unit | 0 - 1 | controlledTerms/UnitOfMeasurement
```

There would be two options a `quantitativeValueArray` could look like then: 

Option 1: An array of 4-tuples with [value, uncertainty, typeOfUncertainty, unit]. 
This would make it possible to have an array of values with different units and types of uncertainty. This is basically like the old `electrode` and `electrodeArray` schemas:

```

Option 2: An array of 2-tuples with [value, uncertainty] and typeOfUncertainty and unit as additional properties (objects with 0-1).  


```
{
  "type": "array",
  "prefixItems": [
    { "type": "number" },
    { "type": "string" },
    { "enum": ["Street", "Avenue", "Boulevard"] },
    { "enum": ["NW", "NE", "SW", "SE"] }
  ]
}
``` 
```
{
  "_type": "https://openminds.ebrains.eu/core/QuantitativeValueArray",
  "required": [
    "value"
  ],
  "properties": {
    "value": {
      "type": "number",
      "_instruction": "Enter the measurement value of this quantitative value."
    },
    "uncertainty": {
      "type": "array",
      "maxItems": 2,
      "minItems": 2,
      "_instruction": "Enter the measurement uncertainty of this quantitative value.",
      "items": {
        "type": "number"
      }
    },
    "typeOfUncertainty": {
      "_instruction": "Add the type of uncertainty used for this quantitative value.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/controlledTerms/TypeOfUncertainty"
      ]
    },  
    "unit": {
      "_instruction": "Add the unit of measurement of this quantitative value.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/controlledTerms/UnitOfMeasurement"
      ]
    }
  }
}

**Comment by UlrikeS91** [comment]
Let's revive this issue. There is something called `prefixItems`, which could be useful in this context (see here for example: https://json-schema.org/understanding-json-schema/reference/array.html).

However, what was the point of having an array of values only allowing the same unit? Couldn't it be just like what we had for the `electrode` & `electrodeArray` schemas? Something like this:

```
{
  "_type": "https://openminds.ebrains.eu/core/QuantitativeValueArray",
  "required": [
    "quantitativeValues"
  ],
  "properties": {
    "quantitativeValues": {
      "type": "array",      
      "minItems": 2,
      "uniqueItems": true,
      "_instruction": "Add two or more quantitative values that are part of this array.",
      "_linkedTypes": [
        "https://openminds.ebrains.eu/core/QuantitativeValue"
      ]
    }
  }
}
```

That would still make it possible to create a `numericalParameter` like @lzehl gave as example in the original PR #177 (where this request was raised):
> "name": "stimulusTriggerPoints",
> "value": [1s, 2s, 4s]

**Comment by lzehl** [comment]
to revive this issue and combine it with a QuantitativeValueRange issue when looking at age:
+ keeping the same unit for all items in a list/in an array is the easiest solution for us
+ with age ranges this is a bit ugly if the range spans over new born (days) to adult (years)...

I still would go with keeping the same unit for all approach. @apdavison what do you think?

**Comment by apdavison** [comment]
If you want different units, you can just use a list of QuantitativeValues, no?

The advantage of QuantitativeValueArray with a single unit is that the representation can be much more concise. (The use case I think is where the array has hundreds or thousands of values).

For the uncertainties, could we use a tuple of arrays rather than an array of tuples?

**Comment by lzehl** [comment]
@apdavison I agree that the main use case for QuantitativeValueArray is to register arrays with large numbers of values. "unit" should be the same then for all values (to keep it simple).

For QuantitativeValueRange we also assume the same for min and max value. This could be changed to allow for more flexibility.  

"For the uncertainties, could we use a tuple of arrays rather than an array of tuples?" you mean rather grouping all + uncertainties and all - uncertainties? this would only work under the assumption that the order of the arrays are preserved correct? Otherwise items that belong together muss be kept in an n-tuple, no?

**Comment by apdavison** [comment]
@lzehl yes, this requires the assumption that array order is preserved. I think this is a reasonable assumption when dealing with arrays.

**Comment by lzehl** [comment]
cf. #337
