### ISSUE TITLE
Question: changes proposed to have a clearer usage of the term "instance"

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#190]
@apdavison @olinux @UlrikeS91 @jagru20 @skoehnen @bweyers @Peyman-N

While writing the paper and the documentation on the future homepage for openMINDS (collab) and presenting the metadata models now several times I've frequently stumbled upon the term "instance". Here are the three aspects that are in connection with this term:

+ For describing information around a single file, we chose the schema label "FileInstance". 
+ We also have an openMINDS_instances repository that contains metadata representations of some schemas where we want the entries in the KG more controlled.
+ We have in openMINDS_controlledTerms a folder "terminologies" that contains metadata representations of the controlledTerms schemas (except for TermSuggestion).

I would like to make this more consistent and like to make the following proposal:
1) Change the schema name "FileInstance" to just "File"
2) Use the term "instance" when speaking about a metadata representation (JSON-LD) of a schema. That way the content of the openMINDS_instances repository is more clearly defined.
2) Move the instances of the "terminologies" in the openMINDS_controlledTerms repository to the openMINDS_instances repository.

What do you think?

**Comment by UlrikeS91** [comment]
> 2. Use the term "instance" when speaking about a metadata representation (JSON-LD) of a schema. That way the content of the openMINDS_instances repository is more clearly defined.

Fine by me :) 

> 3. Move the instances of the "terminologies" in the openMINDS_controlledTerms repository to the openMINDS_instances repository.

Very good suggestion! Absolutely fine by me!

> 1. Change the schema name "FileInstance" to just "File"

Generally not opposed to changing the schema name. What was the reason to have "instance" in the name in the first place? Was it to have a clear solution (and difference) between "fileBundle", "fileRepository" and "file(Instance)"? I think "file" alone would be enough, just curious why it was added in the first place (and making sure that there wasn't any good reason for having it) ;)

**Comment by lzehl** [comment]
@UlrikeS91 I actually do not remember :sweat_smile: But yes I think it was to have clear differentiation between the fileX schemas.
It came out of a discussion with Oli a very long time ago. @olinux do you remember why we decided for "FileInstance" instead of "File"?

**Comment by lzehl** [comment]
Was solved.
