### ISSUE TITLE
The protocolExecution is still using the old SANDS submodule 

### ISSUE THREAD

**Issue by Peyman-N** [openMetadataInitiative/openMINDS_core#206]
@apdavison @olinux @UlrikeS91 @jagru20 @skoehnen @bweyers @Peyman-N
As the `AnatomicalEntity` has been deprecated in new SANDS the `semanticallyAnchoredTo` property should point out to `ParcellationEntity`. 
Another possible solution can be to add both `ParcellationEntity` and `customAnatomicalEntity` as possible link types, this come with added benefit of possibility of adding the new entities on the go, but the drawback is the possibility that users can add anatomical entities that are essentially same as the ones present in atlases. 

https://github.com/HumanBrainProject/openMINDS_core/blob/3253a972b0b877b59298cdd0b1c9de0c5b3c6f46/schemas/research/protocolExecution.schema.tpl.json#L69-L77

**Comment by lzehl** [comment]
@Peyman-N thanks for bringing this up. This property needs to point now to the ParcellationEntity (SANDS) or the UBERONparcellation (controlledTerm). It should not point to a customAnatomicalEntity.  They are separately handled in SANDS and should not be mixed with the controlled relations we want to have in place. Via StudyTarget it is still possible to enter a custom brain region / anatomical entity via the TermSuggestion.

**Comment by lzehl** [comment]
The question is if we want to delete this completely and just have the StudyTarget option

**Comment by Peyman-N** [comment]
Actually, I like the idea of having it as a `controlledTerm`, then with a finite number of regions, the graph representation based on this can be really useful for the end user. 
I recommend we link this to the `UBERONparcellation` as this is just a information concerning the original anatomical region that this `protocolExecution` going to operate on. Based my understanding `StudyTarget` encapsulate the additional information about it. I have no problem with having both of them.
On the same note, I think instruction of studyTarget from following 

> Add all study targets of this model version.

should be changed to 

> Add all study targets of this protocol execution.

**Comment by lzehl** [comment]
This one was solved in PR #204 and #209.
