### ISSUE TITLE
Reference to non-existing AnatomicalEntity 

### ISSUE THREAD

**Issue by olinux** [openMetadataInitiative/openMINDS_core#208]
https://github.com/HumanBrainProject/openMINDS_core/blob/6005a3580d0046e9d18de6758c259739cdd6167f/schemas/research/protocolExecution.schema.tpl.json#L75

AnatomicalEntity doesn't exist anymore - should it be CustomAnatomicalEntity instead?

**Comment by lzehl** [comment]
@olinux semantically Anchored To should be thrown out of protocolExecution entirely. 
It needs to be placed somewhere else (e.g. most likely TissueSample/Collections).

**Comment by lzehl** [comment]
This was solved in #204 & #209
