### ISSUE TITLE
reassessment of hardware as a product in openMINDS_core

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#230]
@apdavison & @Peyman-N & @bweyers & @olinux I tried to gather what we have about hardware:

Within openMINDS_computation, we have the Hardware schema with the following properties:
+ name (free text)
+ version (free text)
+ description (free text)
Idea: to specifically capture here only computer hardware devices.

Within openMINDS_core, SoftwareVersion references via property "device" to the controlledTerms/OperatingDevice. 
This currently holds the following instances: 
+ desktop
+ embedded system
+ high performance computer
+ mobile 
+ server
+ web

Within openMINDS_ephys, we have the Device schema with the following properties: 
+ manufacturer (free text)
+ model name (free text)
+ internal identifier
+ serial number
+ description
+ device type (link to controlledTerms/DeviceType)
+ software (link to core/SoftwareVersion)

The controlledTerms/DeviceType holds currently only the following instance as example what to expect:
+ magnetic resonance imaging scanner

Considering all of this I think we need to reconsider:
1) renaming SoftwareVersion property "device" to "operatingDevice"
2) rename Hardware schema in computation ComputerHardware
3) introducing a Hardware schema in openMINDS_core

**Comment by lzehl** [comment]
Could you give me your thoughts on:
+ would hardware also need a Hardware  +  HardwareVersion schema ?
+ what properties should be covered ? are the ones above sufficient ?
+ if ComputerHardware in computation would inherit from Hardware in core; do the properties fit ?

**Comment by Peyman-N** [comment]
I completely agree with the three proposition. 
But I think it would worth the effort to consider elaborate it a little more by adding something like a hardware setup. 
By adding this feature we can daisy chain some Hardware schema's and create more complex Hardware's. 
I played with the idea a little bit and it should be doable just by adding a property called hasParent or consistsOf.

**Comment by apdavison** [comment]
> * would hardware also need a Hardware  +  HardwareVersion schema ?

What we have in computation/Hardware at present is effectively HardwareVersion, and I think that's probably enough.

> * what properties should be covered ? are the ones above sufficient ?

`Device.model name` serves perhaps the same role as `Hardware.name`? Can we perhaps merge these to avoid redundancy.

> * if ComputerHardware in computation would inherit from Hardware in core; do the properties fit ?

It's unclear which properties you propose to put in `core.Hardware`

**Comment by Peyman-N** [comment]
Inquiring about this comment as it would affect the openMINDS-ephys.

**Comment by lzehl** [comment]
I guess we need to start setting up a first draft for the **openMINDS_core/Hardware(Version)** schema.
Here a suggestion of properties (to be discussed):

+ **full name** (string | format: free text | count: 1 | required)
+ **short name** (string | format: free text | count: 1 | required)
+ **manufacturer** (string | format: free text | count: 1 | required)
+ **serial number** (string | format: free text | count: 1 | required)
+ **version identifier** (string | format: free text | count: 1 | required)
+ **device type** (link to controlledTerms/DeviceType | required)
+ **is new version of** (link to core/Hardware | count: 1 | optional)
+ **description** (string | format: free text | count: 1 | optional)
+ **software** (link to core/SoftwareVersion | optional)

@Peyman-N I would argue that a "Setup" of multiple Hardware devices should be handled separately.
@apdavison is there a reason why you did not capture "serial number" in openMINDS_computation?

Do we really want to capture the individual device (identified by serial number)?   
OR would it be sufficient to capture manufacturer, name and version?

**Comment by jcolomb** [comment]
I would add a PID entry:
it seems hardware can have a RRID,
open hardware (or their documentation) often have a doi, similar to software, often via zenodo.

**Comment by apdavison** [comment]
In openMINDS_computation we are interested in computer hardware, for which a serial number is rarely of interest. It makes sense to have it here, but I would make it optional.

I also think version identifier should be optional.

What is the idea behind the software field? Is this for firmware? For computer hardware this field should not be used for the operating system, rather one should use Environment from openMINDS_computation.

**Comment by jcolomb** [comment]
Just bumped into https://github.com/rdawg-pidinst/schema, this is a metadata schema developed in a RDA working group  https://www.rd-alliance.org/groups/persistent-identification-instruments-wg
I wonder if there are connections to make.
