### ISSUE TITLE
Enable for curating software tutorials

### ISSUE THREAD

**Issue by jagru20** [openMetadataInitiative/openMINDS_core#254]
In the HLST meeting, the idea came up to introduce a schema dedicated to curate tutorials in addition to the documentation of a software. Some questions regarding this topic are:
- Could a tutorial be covered by the property "otherContribution" with a new ContributionType "Tutorial"?
- What defines a Tutorial, how to separate it from documentation?
- What properties are necessary to curate about a tutorial in the KG?

Maybe @bweyers  and @heplesser can give some more detail on the thoughs leading to this idea.

**Comment by lzehl** [comment]
@jagru20 This is an interesting request that is similar to another issue #211 

"otherContribution" is meant for legal persons (mainly persons) so I think it is probably not the right spot to link the actual tutorial (only the tutor). 

Possibilities I see: a new field "supplementary material" (cf. #211) or "related publication". 

@bweyers and @heplesser Looking forward to hear more about the details of this idea.

**Comment by jagru20** [comment]
This could in fact be a duplicate of #211, should we think about continuing the discussion there?

**Comment by lzehl** [comment]
Yes. If #211 fits your needs / idea then please continue the discussion there.

**Comment by heplesser** [comment]
Yes, this is covered by #211, so @jagru20, please close this one.

**Comment by jagru20** [comment]
Discussed in #211
