### ISSUE TITLE
Support files inside a zip container in the FILE scheme

### ISSUE THREAD

**Issue by dickscheid** [openMetadataInitiative/openMINDS_core#257]
We sometimes have to link files which are orginally hosted with other files inside a zip archive - for example, the tissue mask of the ICBM 152 brain template. To identify such files, it would be helpful to add fields that allow to 1) identify the downloadable file under the URL as a container file (like zip, tarball, ...), and 2) specify the target filename inside that container, which could only be obtained after retrieving and extracting the container..

**Comment by lzehl** [comment]
@dickscheid thank you for raising this issue :) 

@olinux and @skoehnen I think that this is an interesting feature we could add. Any ideas on how we could provide this?
@apdavison and @bweyers this issue may also be of interest for you I think. what do you think?
