### ISSUE TITLE
FileBundle updates (grouping & descendedFrom)

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#259]
discussed offline with @lzehl 
1. descendedFrom should be 0 - 1, because it shouldn't be more than what the FileBundleGrouping states
2. fileOrigin category need to be added to all specimen(set)s as well, because a file bundle could begrouped by e.g. a subject and collect data for more than one state

FYI @olinux

**Comment by lzehl** [comment]
@UlrikeS91 can you take this over?
