### ISSUE TITLE
change URL in serviceLink to embeddedType?

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#281]
@olinux what do you think?

**Comment by UlrikeS91** [comment]
Do you mean an IRI or the core schema for URL? The latter isn't possible, is it? If I remember correctly, then URL cannot be a linked type in other schemas anymore, or?

**Comment by lzehl** [comment]
@UlrikeS91 the property "openDataIn" in the ServiceLink schema has as _linkedTypes the URL schema currently. Making it an embeddedType only means that this particular service link url cannot be used by another schema which it never will (since it is specific for the service link). Therefore I suggest to change the URL for the property "openDataIn" in the ServiceLink schema to an embeddedType.
