### ISSUE TITLE
Incorrect Python content types

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#287]
`application/text/x-python.3` should be `text/x-python.3` and similarly for the other Python content types. We should also add simply `text/x-python` for code where we don't know the version, or code that is compatible with both Python 2 and Python 3.

**Comment by lzehl** [comment]
@apdavison & @jagru20 was this issue solved with the #290? The PR is approved as far as I can see should we merge it?

**Comment by apdavison** [comment]
done
