### ISSUE TITLE
Add Property "shortBio" to person schema

### ISSUE THREAD

**Issue by jagru20** [openMetadataInitiative/openMINDS_core#288]
I have just got a request to add a short bio to the person information. I wanted to bring this to discussion, as I did not find a place to sensibly integrate this kind of info. The question here is, if the KG should provide space for this information. 

If yes, I would suggest adding an optional property of type string that is limited to e.g., 500 characters.

**Comment by lzehl** [comment]
@jagru20 thanks for bringing this up. Originally we though we leave all person information to be handled by the person via ORCID and linking to the public ORCID page of that person via the KG. We thought that this would keep maintaining that information to a minimum. Now we added affiliations nonetheless... 

@HumanBrainProject/openminds-developers what do you think?

**Comment by jagru20** [comment]
Yes, that's what I thought. In fact, I tend not to include the feature, I just want to have it discussed/decided once so that I can respond accordingly in future requests as well.

**Comment by UlrikeS91** [comment]
I think that there is a difference between affiliation and a short bio. Stupid example maybe, but imagine two persons with the same name. An affiliation would help to distinct between them (and the ORCID obviously, but not directly in the KG in a human understandable way). A short bio may help with that too, but could potentially also be similar and not help much. 

Both require maintenance but affiliations much less than a short bio. I would like to not add any more fields that need regular maintenance. Short bios seem like a large effort for very little added value, and researchers can always provide an ORCID and maintain their own bio there instead. So, I would vote against adding it as a property.

**Comment by lzehl** [comment]
Let us close this issue for now. We should reevaluate the Person and Organization schemas once visualization of those elements is more tested
