### ISSUE TITLE
adding QuickNII contentTypes

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#292]
**ContentType schema:** 
+ https://humanbrainproject.github.io/openMINDS/v3/ **--> select** core/DATA/ContentType
+ https://github.com/HumanBrainProject/openMINDS_core/blob/v3/schemas/data/contentType.schema.tpl.json

**required property:** name
**recommended property:** extension, as well as description AND/OR link to specification

**Missing contentTypes (suggested names):**
+ application/vnd.quicknii+json
+ application/vnd.quicknii+xml
+ application/vnd.quicknii+flat

**Comment by UlrikeS91** [comment]
@Tevemadar and @majpuc can be asked for further questions
