### ISSUE TITLE
add MeshView contentTypes

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#293]
**ContentType schema:** 
+ https://humanbrainproject.github.io/openMINDS/v3/ **--> select** core/DATA/ContentType
+ https://github.com/HumanBrainProject/openMINDS_core/blob/v3/schemas/data/contentType.schema.tpl.json

**required property:** name
**recommended property:** extension, as well as description AND/OR link to specification

**Missing contentTypes (suggested names):**
+ application/vnd.meshview+json
+ ??? (some text file)

**Comment by UlrikeS91** [comment]
@Tevemadar and @majpuc can be asked for further questions

**Comment by Majpuc** [comment]
For the Nutil Quantifier output json: The coordinate files are identical across the board, from Nutil v0.33 to v0.8.0.

**Comment by MaaikevS** [comment]
As discussed in the PR #332, the meshview contentType mentioned in this issue is rather a Nutil contentType.
@Majpuc Unless there are other contentTypes for Meshview that need to be mapped, we can close this issue.

**Comment by Majpuc** [comment]
Did we want to create a content type for the manually input [x1, y1, z1, x2, y2, z2,..., xn, yn, zn] values or not? If not, we can close this issue.

**Comment by MaaikevS** [comment]
@lzehl I think you may want to create another contentType for the meshview input that is saved as a csv file?
The coordinates would be stored as follows:
![image](https://user-images.githubusercontent.com/31585951/175242924-de02674e-e179-44c3-9131-3314c2f54e33.png)
You would just copy paste the coordinates (so not the headers) into the "cloud from coordinates" field.

**Comment by lzehl** [comment]
I would define it yes. Probably as application/vnd.meshview.coord+csv

What I do not understand how the CSV you show above match with the input structure you stated before ([x1, y1, z1, x2, y2, z2,..., xn, yn, zn]). Maybe this is just a misunderstanding... but the above CSV would translate to a list of list I think  ([[x1, y1, z1], [x2, y2, z2],..., [xn, yn, zn]]). @apdavison could you have a look? I may just get it wrong...

**Comment by MaaikevS** [comment]
So the input structure we discussed above ([x1, y1, z1, x2, y2, z2,..., xn, yn, zn]) is for how the coordinates are stored in the meshview compatible json file. This is different from the way the CSV is organised.

**Comment by Tevemadar** [comment]
While the format itself is under change at the moment, it looks like this:
```
[
   {
      "r":0, "g":255, "b":0, "name":"Green sphere", "count":2,
      "triplets":[
         298.95407813357224, 487.6609236653011, 296.9371615458696,
         272.5004943278949, 429.9051730261476, 282.55975012476176
      ]
   },
   {
      "r":255, "g":0, "b":0, "name":"Red cube", "count":1,
      "triplets":[
         268.74301989920855, 529.4377452726583, 165.1498753426239
      ]
   }
]
```
The gist of it is that a cloud has a color (`rgb` fields, all of them in the range of 0-255), a display `name`, and the points. Right now there is an actual `count` field and so `triplets` are expected to contain 3*`count` coordinates. There are a couple more, optional fields too, not shown here.

This is "MeshView JSON".

**Comment by MaaikevS** [comment]
Thanks @Tevemadar.
We have already taken care of this one in PR #332 as a nutil output that can be used as a meshview input.

We are now discussing the format of the values (e.g. csv) that could be pasted into the "cloud from coordintates" section in MeshView.

**Comment by Majpuc** [comment]
@lzehl do you need more information for this content type?

**Comment by lzehl** [comment]
@Majpuc is the CSV mentioned above the one you suggested in #294 ? The meshview file was changed to : [nutil.quantifier+json.jsonld](https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/nutil.quantifier%2Bjson.jsonld) BUT is this correct? When this JSON is defined by meshview the content type is not from nutil but meshview and nutil is just using it. please clarify

**Comment by Majpuc** [comment]
Yes, I understand that this can be confusing. Meshview is opening the Nutil quantifier Json files, so this is correct. Meshview is outputing only a png file.

**Comment by lzehl** [comment]
perfect. thanks for the clarification!

**Comment by lzehl** [comment]
with closing #294 this one should be solved as well.
