### ISSUE TITLE
add Nutil contentType

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#294]
**ContentType schema:** 
+ https://humanbrainproject.github.io/openMINDS/v3/ **--> select** core/DATA/ContentType
+ https://github.com/HumanBrainProject/openMINDS_core/blob/v3/schemas/data/contentType.schema.tpl.json

**required property:** name
**recommended property:** extension, as well as description AND/OR link to specification

**Missing contentTypes (suggested names):**
+ application/vnd.nutil.quantifier (extension: .nut)
+ application/vnd.nutil.transform (extension: .nut)
+ application/vnd.nutil+csv
+ image/vnd.nutil+png

**Comment by UlrikeS91** [comment]
@leuat, @sharoncy and @majpuc: Are the .nut file for Nutil all the same regardless of which function is used (e.g. Transform vs. Quantifier)?

**Comment by sharoncy** [comment]
No they are different. The .nut file structure also varies between Nutil versions.

**Comment by UlrikeS91** [comment]
> No they are different. The .nut file structure also varies between Nutil versions.

Thank you for the rapid response, @sharoncy. 

So, this means that we will need to add 4 contentTypes for the nut file extension - one per function:
- Transform
- Quantifier
- TiffCreator
- Resize

Correct?

**Comment by sharoncy** [comment]
I discussed this with Ulrike in person: 4 contentTypes for the nut file extensions is a good idea. To fit with the OpenMINDS schema she suggested sharing the different Nutil features as different "software", each linked to a different contentType (so a different KG datacard for Nutil Quantifier, Transform, Resize and TiffCreator). This sounds like a good idea as the Nutil features are standalone. But this may have implications elsewhere, let's discuss @Majpuc and @leuat .

**Comment by Majpuc** [comment]
Thank you for the info. This is going to be tricky as the software that are registrered in the KG  need to have corresponding descriptions in the TC documents. Currently, we have one ID for Nutil as a whole and one ID for Nutilweb as a whole, because the web version will have a different access point and don't allow all features. They also use different content types. What do you think @leuat? We discussed this a lot during the meeting yesterday. I propose to have a meeting about this in order to give you a bit more background information.

**Comment by sharoncy** [comment]
Yes please, I am not fully informed. @leuat @Majpuc

**Comment by lzehl** [comment]
@sharoncy you said the nut files are also different between nutil versions? meaning how many versions should we cover for the 4 nut files?

**Comment by sharoncy** [comment]
We will have to discuss this and get back to you. @Majpuc @leuat

**Comment by Majpuc** [comment]
Hi, some considerations and questions:

1. There are 9 versions of Nutil on NITRC. Only 3 of them are listed on EBRAINS (0.33, 0.403, 0.7.0). Do you want content type for all of them? v0.33 did not have a .nut file but an Excel template. If we are sticking to v0.403 and 0.7.0 then there are 2 versions of the nut file. If we are interested in all 9 versions then we'll have to go back and compare. Many of them are intercompatible (for example the nut files from v0.7.0 can be used with v0.8.0). 

2. As Sharon mentioned above:  4 contentTypes for the nut file extensions is a good idea. To fit with the OpenMINDS schema she suggested sharing the different Nutil features as different "software", each linked to a different contentType (so a different KG datacard for Nutil Quantifier, Transform, Resize and TiffCreator).

**Comment by MaaikevS** [comment]
@lzehl @jagru20 Could you have a look at Maja's comment and let me know your thoughts?
I am happy to make the contentType instances once we have settled on them. Let's try to get this issues closed asap!

**Comment by jagru20** [comment]
I think the only thing I can really comment on at this point is, that curating the nutil features as different softwareVersion instances would be no problem, as they can still be linked to the nutil software instance. In fact, this could possibly be a use case for the "isAlternativeVersionOf" property, what do you think @lzehl? 
Alternatively we can also split them on the ResearchProduct (i.e. Software) level.

**Comment by lzehl** [comment]
For point 1 in @Majpuc last comment:
I actually would suggest (in the long run) to register all Nutil versions in EBRAINS to have a full representation. Respective contentTypes (if they are version dependent) need to be generated in that case.

I have a question for point 2 in @Majpuc last comment before I can answer:
Are the Nutil "features" independent software components, meaning can they be installed independent of each other?

**Comment by Majpuc** [comment]
Point 1: Yes, indeed
Point 2: No, all the features are available in the same package.

**Comment by Majpuc** [comment]
Hi @lzehl 
I've reassessed this issue. We have 4 released versions of Nutil that are working properly and shared through KG. It turns out that all "flavors" of  the .nut files can be open in the software, regardless of the feature or version. The feature is recognized automatically and there is no need to specify it. 
Would it be possible to have only these content types:

    application/vnd.nutil (extension: .nut)
    application/vnd.nutil+csv
    image/vnd.nutil+png

**Comment by lzehl** [comment]
@Majpuc thanks for picking up this issue again. I'll add the first two content types for nutil asap. For the third (the image) I'll just want to ask if it is really a special nutil PNG? Or is just a PNG created by nutil with no special elements (that only nutil can read/interpret)?

**Comment by Majpuc** [comment]
Thanks @lzehl the png's generated by Nutil are just regular png files, nothing special about them.

**Comment by lzehl** [comment]
@Majpuc then the png is just the regular png content type for nutil. Another question though: 

There is already one content type for nutil registered [instances/data/contentTypes/nutil.quantifier+json.jsonld](https://github.com/HumanBrainProject/openMINDS_core/blob/v4/instances/data/contentTypes/nutil.quantifier%2Bjson.jsonld). Is this still a valid content type or does it need to be removed?

**Comment by lzehl** [comment]
@Majpuc I need more information on what the *.nut and *.csv files are used for in nutil (what is their purpose).

**Comment by Majpuc** [comment]
The .nut file is listing the analysis parameters, so in a sense it contains the metadata of the run. 
The .csv file is an output result file. It consists of a serie of tables giving the quantification of objects per regions, load, etc..

**Comment by Majpuc** [comment]
The json content type is still valid. It is one of the output files allowing to visualise the objects as point clouds in MeshView.

**Comment by lzehl** [comment]
@Majpuc done. The content types should appear for EBRAINS sometime tomorrow.
