### ISSUE TITLE
add Ilastik contentTypes

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#296]
**ContentType schema:** 
+ https://humanbrainproject.github.io/openMINDS/v3/ **--> select** core/DATA/ContentType
+ https://github.com/HumanBrainProject/openMINDS_core/blob/v3/schemas/data/contentType.schema.tpl.json

**required property:** name
**recommended property:** extension, as well as description AND/OR link to specification

**Missing contentTypes (suggested names):**
+ application/vnd.ilastik+hdf5 (extension: .ilp)
+ application/vnd.ilastik+csv
+ image/vnd.ilastik.prediction+png
+ image/vnd.ilastik.prediction+jpeg
+ image/vnd.ilastik.prediction+hdf5
+ image/vnd.ilastik.prediction+tiff
+ image/vnd.ilastik.prediction+tiff-stack
+ image/vnd.ilastik.segmentations+png
+ image/vnd.ilastik.segmentations+jpeg
+ image/vnd.ilastik.segmentations+hdf5
+ image/vnd.ilastik.segmentations+tiff
+ image/vnd.ilastik.segmentations+tiff-stack
+ ???

**Comment by Majpuc** [comment]
Validation can be requested to Tomaz Viera, EMBL https://github.com/Tomaz-Vieira

**Comment by lzehl** [comment]
This issue was solved with #309
