### ISSUE TITLE
Add ISSN to list of digital identifiers

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#338]
needed by the "publications" module, to identify journals

https://www.issn.org
https://en.wikipedia.org/wiki/International_Standard_Serial_Number

The pattern should be something like `^[0-9]{4}-[0-9]{3}[0-9xX]$`

**Comment by lzehl** [comment]
@apdavison yes. I'll prepare a PR for you to review.

**Comment by apdavison** [comment]
That was quick! Many thanks @lzehl !
