### ISSUE TITLE
Atlas and Common Coordinate Spaces on level of RP/RPV

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#343]
Atlases or specifically their parcellations are often as whole used / applied to data in other studies. Currently the usage of a whole atlas can only be registered via the top level Parcellation Entity of an atlas (if that exists) under "study target". I think it would be cleaner and more accurate to allow Brain Atlas Versions as input data in this context. In addition individual brain regions of that atlas still can be added as study targets if applicable.

Same idea holds for common coordinate spaces. A transformation of data always requires the common coordinate space as input. 

@tgbugs @UlrikeS91 what do you think?

**Comment by lzehl** [comment]
If the others agree @olinux this would mean for EBRAINS to visualize "data input" soon.

**Comment by UlrikeS91** [comment]
I think this sound valid. For several of our own datasets from Oslo, this would be very useful to have. One could add the underlying datasets for the atlases, but then things like to coordinate space would be missing, which is crucial information.

Is your idea to allow BOTH brain atlases and common coordinate spaces to be options to link under "input data"? I'm not sure if the latter would make sense without an atlas. I know that it is technically possible to just transform data based on a coordinate space but generally it is done to relate it to other data in the same space (so either the atlas or other data that used the atlas as input). Wouldn't the atlas link be enough? I may misunderstood, though.

**Comment by lzehl** [comment]
@UlrikeS91 yes both brain atlas versions and common coordinate spaces should be added as "input data". 

The common coordinate spaces are frequently used to transfer multiple patient data into the same space to display them for example in overlays without the aim of using an atlas in addition. Also some coordinate spaces actually allow immediate relation to multiple atlases without the data that were transformed to this space really aiming for that relation (it just happens on the side).

I know that this steps means that for EBRAINS we need to push as well for the SANDS visualization of Atlases and Coordinate Spaces in the EBRAINS KG because then the cross linkages between data through atlases and coordinate spaces  as well as the cross relations between atlases through their coordinate spaces become really evident. @UlrikeS91 that means we need to complete the already registered brain atlases and coordinate spaces (so that they become informative enough to be displayed in the KG Search) and @olinux that we meet to discuss visualization of atlases and common coordinate spaces in the KG Search.

**Comment by UlrikeS91** [comment]
Ok. Your use case makes sense. Then it should be fine to have both as options. 

We can discuss the atlases at some point. From the rodent side, Waxholm atlas is pretty complete, but Allen atlas is lacking quite a bit of information...

**Comment by lzehl** [comment]
@UlrikeS91 okay. I'll prepare the PR
@olinux let's discuss visualization of input data soon for EBRAINS

**Comment by lzehl** [comment]
@UlrikeS91 quick follow up question: only BAV as input or also BA ?

**Comment by UlrikeS91** [comment]
> @UlrikeS91 quick follow up question: only BAV as input or also BA ?

I would say only BAV. Is there a use case where all versions of an atlas have been used as input data? This would be the only reason to allow BA as well.

**Comment by lzehl** [comment]
@UlrikeS91 agreed the use case of all versions as input is unlikely and can be covered by listing them all. I'll make the PR asap
