### ISSUE TITLE
Registration of Data Use Agreements as licenses?

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#345]
https://data.donders.ru.nl/doc/dua/RU-DI-HD-1.0.html?1

@apdavison and @UlrikeS91 specifically for externally published data, should we register DUAs as licenses (similar to the HDG EBRAINS DUAs we registered)?

**Comment by apdavison** [comment]
for clarity, I suggest adding a new schema for DUAs

**Comment by UlrikeS91** [comment]
A separate schema for DUAs is probably smarter. They do not have the same field as licenses and we already agreed when we added the EBRAINS DUAs that this is not a pretty fix but a good enough workaround for now. If we want to expand on this list, we should maybe fix it properly now.

**Comment by lzehl** [comment]
@apdavison and @UlrikeS91 I agree with the both of you but we didn't do this for EBRAINS at the moment either because it entails a longer discussion (politically).

If you have a concrete suggestion that we could quickly implement (openMINDS is less of an issue here) and properly define a way of handling this in EBRAINS (display wise in the KG and politically wise because of missing licenses) please tell :) 

Otherwise I suggest we continue the workaround for now and get back to it later. 

What do you think?

**Comment by UlrikeS91** [comment]
I assume that there won't be a quick solution, but we should raise this issue anyway. Until then, if you need the other DUAs urgently, I would agree that we stick to the workaround for now.

**Comment by lzehl** [comment]
we can come back to finding a better solution later on in a separate issue. thanks for your quick feedback and support with this one.
