### ISSUE TITLE
adding 'performedBy' for ProtocolExecution or Activity

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#353]
@apdavison @Peyman-N you should review this issue critically to see if this fits also for extensions

We (@UlrikeS91 and me) are thinking to add an optional 'performedBy' / 'agent' property to the ProtocolExecution.
I know that you typically ask for this info also for the extensions. Should we therefore add it rather to Activity (so that all extending schemas inherit the field)?

**Comment by Peyman-N** [comment]
I prefer to have it in activity so the extensions can inherit it too. Originally there was a property named `agent` in the ephys and MRI. Beside that, this is an integral part of provenance information that we should capture. 
@apdavison what do you think?

**Comment by apdavison** [comment]
To be honest, I thought it was already in Activity!

**Comment by lzehl** [comment]
@Peyman-N and @apdavison :smile: then this is a clear GO for adding it to Activity. Which property name do you prefer ? ( aslo @UlrikeS91 ) I don't have a strong opinion.

**Comment by apdavison** [comment]
In computation, we have the field "startedBy", since computations are assumed to be automated ones. W3C PROV uses "wasAssociatedWith" for the direct link, together with an optional "[qualifiedAssociation](https://www.w3.org/TR/prov-o/#narrative-example-qualified-4)" to specify the role taken by the agent. Simply "agent" would also be ok.

**Comment by lzehl** [comment]
So if we add this now to Activity then it needs to work for all extended schemas. 

If you use "startedBy" in computation maybe "performedBy" (linking to -> SoftwareAgent, Person) would be a good option for all? 
"agent" might not be so intuitive as "performedBy".

Independent of the property name: we could also point to Contributing instead of Person to include the role that person played in the performance. We potentially have to reconsider though for this a bit the Contributing schema (name, and associated instances for roles). I'm open to make these changes since I was anyway not so happy currently with the schema and it is barely used as far as I know.

@apdavison @Peyman-N @UlrikeS91 what do you think?

**Comment by UlrikeS91** [comment]
> So if we add this now to Activity then it needs to work for all extended schemas.
> 
> If you use "startedBy" in computation maybe "performedBy" (linking to -> SoftwareAgent, Person) would be a good option for all? "agent" might not be so intuitive as "performedBy".

I agree that "performedBy" is more intuitive and should fit all the examples that were mentioned here. 

> Independent of the property name: we could also point to Contributing instead of Person to include the role that person played in the performance. We potentially have to reconsider though for this a bit the Contributing schema (name, and associated instances for roles). I'm open to make these changes since I was anyway not so happy currently with the schema and it is barely used as far as I know.

What is the exact problem with the `Contribution` schema? As you said, it contains the `ContributionType` (--> controlledTerms/ContributionType) and the `Contributor` (--> core/Person). 

For the example where I need this property, they would like to add the person that collected the data (aka data collector). That could be the contribution type and then the person is linked under contributor. This works just fine. 

For software agents, you would not use this anyway but use the `SoftwareAgent` instead. 

Would you want to only have `Contribution` and `SoftwareAgent` as options for the "performedBy" property or also allow `Person` (without a specific role then) as an option? I think both options would work, but allow all 3 would make it more flexible (without doing much harm).

**Comment by lzehl** [comment]
I think we all agree on the action point that we'll add performedBy to Activity schema.

This property should for sure link to softwareAgent and Person.

The issue I raised about the Contributing schema is a semantic one. It should be called Contributor and not Contributing and it should be ContributorRole not contributingRole... This is only a slight difference but it makes a difference for finding/mapping to terminologies and ontologies. Since this discussion is though a bit of topic here I suggest we move this is to another issue.

I'll try to make the PR for this issue asap.
