### ISSUE TITLE
Service link - data location: updates needed

### ISSUE THREAD

**Issue by UlrikeS91** [openMetadataInitiative/openMINDS_core#357]
In an offline meeting with @apdavison , @Peyman-N and @lzehl, we discussed a `recording` schema. This schema will have a property called `dataLocation`, which is the same property used for the `service link` schema. 
However, we discussed that the options for data location for service links are not ideal. For recording, the linked types are both `file` and `file bundle` (service links only allow file bundles). 

We need to adjust this for the service link schema as well.

**Comment by lzehl** [comment]
@UlrikeS91 did we solve this in the meantime or did we overlook that we already allowed the service link to provide file, file bundle (+ file archive, parcellation entity version, live paper resource item) under data location? cf:

https://github.com/HumanBrainProject/openMINDS_core/blob/v4/schemas/data/serviceLink.schema.tpl.json

I think with this we can close this issue correct?

**Comment by UlrikeS91** [comment]
Good question, but I guess it doesn't matter what happened 😆 It's already part of the schema, so we can close the issue.
