### ISSUE TITLE
request: add "consortium" as legal person 

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#360]
There is a request from @maciej-jedynak to add a "consortium" schema as legal person

Definition: 
A consortium is an association of two or more individuals, companies, organizations or governments with the objective of participating in a common activity or pooling their resources for achieving a common goal. (https://en.wikipedia.org/wiki/Consortium)

I was thinking of making a simple schema: 
+ shortName
+ fullName
+ members
+ homepage
+ contactInformation

@apdavison @olinux @UlrikeS91 @bweyers what do you think?

**Comment by apdavison** [comment]
ok with me

**Comment by UlrikeS91** [comment]
Same here. Sounds useful, no objections 🙂

**Comment by lzehl** [comment]
@olinux & @bweyers I will implement this request then. @olinux once it's done the EBRAINS KG (Editor & Search) needs an update I assume.
