### ISSUE TITLE
adding other user IDs to Person schema

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#368]
@apdavison you raised this issue within EBRAINS but I think it belongs here. 

Idea: besides defining the globally unique digital identifiers of a Person, allow a Person to specify user IDs for different accounts of interest (e.g. EBRAINS IAM, but also GitHub, GitLab, etc.)

Potential solution: 
- add 'accounts' (or ?) property to Person schema that links to (0-N) new UserAccount schema
- UserAccount schema properties:
  - accountType (-> link to UserAccountType ? in controlledTerms; terms: GitHub, GitLab, EBRAINS, etc OR would that link to an Organization?)
  - userName (string)

**Comment by lzehl** [comment]
@HumanBrainProject/openminds-developers please have look and make suggestions

**Comment by apdavison** [comment]
for account type, I would use the WebService schema, which I originally proposed for openMINDS_computation but I now think should go in core (see https://github.com/HumanBrainProject/openMINDS_computation/pull/18#issuecomment-1327169079)

**Comment by lzehl** [comment]
@apdavison that is a good idea. But I do have some questions then about how you want to register a WebService. Because I don't see the current suggestion fit for GitHub or GitLab (but maybe I misunderstand it). What would be the version in these cases and who are the developers?

**Comment by apdavison** [comment]
For GitHub, the developer would be the Github organisation, version "v1" or "n/a"

For self-hosted Gitlab, the developer would be GitLab Inc, I guess, and then the version number would reflect whichever version of the Gitlab software has been deployed.

**Comment by lzehl** [comment]
@apdavison could you define the GitLab of EBRAINS as example?

Would that not also mean that we should make Web Services controlled instances of openMINDS? (since they would be valid for typically many cases) New ones should then be requested through openMINDS GitHub.

**Comment by apdavison** [comment]
Something like this:
```
{
    "@id": "...",
    "@type": [
        "https://openminds.ebrains.eu/core/WebService"
    ],
    "https://openminds.ebrains.eu/vocab/fullName": "EBRAINS GitLab",
    "https://openminds.ebrains.eu/vocab/shortName": "EBRAINS GitLab",
    "https://openminds.ebrains.eu/vocab/hasVersion": [
      {
        "@id": "... (id of WebServiceVersion)"
      }
    ],
    "https://openminds.ebrains.eu/vocab/homepage": {
      "@id": "... (id of URL pointing to https://gitlab.ebrains.eu/api/v4)"
    },
    "https://openminds.ebrains.eu/vocab/description": "EBRAINS GitLab is ....",
    "https://openminds.ebrains.eu/vocab/custodian": {
        "@id": "... (id of EBRAINS Organization)"
    },
    "https://openminds.ebrains.eu/vocab/developer": {
        "@id": "... (id of GitLab Inc. Organization)"
    }
  }
```

```
{
  "@id": "...",
  "@type": [
    "https://openminds.ebrains.eu/core/WebServiceVersion"
  ],
  "https://openminds.ebrains.eu/vocab/repository": {
    "@id": "... ID of repository containing the source code for this version of GitLab"
  },
  "https://openminds.ebrains.eu/vocab/keyword": [
    "Public domain software",
    "Continuous Integration / Continuous Deployment"
  ],
  "https://openminds.ebrains.eu/vocab/applicationCategory": [
    {
      "@id": "... taken from SoftwareVersion, maybe applicable here?"
    }
  ],
  "https://openminds.ebrains.eu/vocab/supportChannel": [
    "https://ebrains.eu/support"
  ],
  "https://openminds.ebrains.eu/vocab/versionIdentifier": "Community Edition 14.10.5",
  "https://openminds.ebrains.eu/vocab/shortName": "EBRAINS GitLab",
  "https://openminds.ebrains.eu/vocab/releaseDate": "2022-01-26",
  "https://openminds.ebrains.eu/vocab/homepage": {
    "@id": "... (id of URL pointing to https://gitlab.ebrains.eu/api/v4)"
  },
  "https://openminds.ebrains.eu/vocab/feature": [
    {
      "@id": "... taken from SoftwareVersion, maybe applicable here?"
    }
  ],
  "https://openminds.ebrains.eu/vocab/inputFormat": [
    {
      "@id": "... id of content type"
    },
    {
      "@id": "... id of content type"
    }
  ],
  "https://openminds.ebrains.eu/vocab/accessibility": {
    "@id": "... id to indicate whether an account is needed to access the web service"
  },
  "https://openminds.ebrains.eu/vocab/versionInnovation": "what's new....",
  "https://openminds.ebrains.eu/vocab/fullDocumentation": {
    "@id": "https://gitlab.ebrains.eu/help"
  }
}

```

**Comment by apdavison** [comment]
I would not make WebServices controlled instances, for the same reason Software does not use controlled instances.

**Comment by lzehl** [comment]
@apdavison okay and thank you for the example. then let's keep them user defined for now. 

What about the changes now in the Person schema?
+ add 'accounts' (or do you have a better name?) property to Person schema that links to (0-N) new UserAccount schema
+ UserAccount schema properties: 
   + accountType (-> link to WebService)
   + userName (string)

**Comment by jcolomb** [comment]
hi.

I am wondering If a "no, we will not implement this" would not be a better answer. If people want us to find them via other accounts, they can provide these accounts on orcid.

it seems only to make things more complicated for the schema and the users, with no advantage on the data collected (these UserAccounts will not be computer readable anyway, or not better than what you can get via the orcid API). On the other hand, this is personal data, which brings a lot of unnecessary data protection issues.

This will only be an extra entry in the form, people will feel responsible to fill it up, and they will be angry about having to do that extra work.

**Comment by apdavison** [comment]
@lzehl yes, I like your suggestion for the changes to Person. For UserAccount I would suggest "service" rather than "accountType" as the property name.

@jcolomb our main use case is to link EBRAINS user accounts to people in the KG, so that if someone adds metadata to the KG with an EBRAINS auth token, we can identify unambiguously which KG Person their metadata should be linked to. This is something which any data repository is likely to want to do.

**Comment by lzehl** [comment]
@apdavison what's your opinion on where to place the UserAccount schema ? actors or miscellaneous ?

**Comment by apdavison** [comment]
I think "actors", since it's most similar in purpose to ContactInformation.

**Comment by lzehl** [comment]
@apdavison I've made the PR https://github.com/HumanBrainProject/openMINDS_core/pull/371 
If it looks good, feel free to merge and delete the branch afterwards.

@olinux we need to discuss if we add accountInformation to the restricted space in EBRAINS (for now).
