### ISSUE TITLE
adding identifiers.org identifiers as digital identifiers

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#372]
cf scheme:
https://docs.identifiers.org/articles/docs/identification_scheme.html

should definitely be an option for DSV digitial identifier (example neurovault). potentially also elsewhere? 
@apdavison @bweyers @UlrikeS91 @skoehnen @olinux @jagru20 please comment

**Comment by UlrikeS91** [comment]
Draft in #378
