### ISSUE TITLE
Change URL to AccessMethods

### ISSUE THREAD

**Issue by skoehnen** [openMetadataInitiative/openMINDS_core#4]
During a discussion during our frontend meeting we came to the conclusion that it makes sense to add the possibility to support more than one way to access the file (CSCS Download, Image-Service).

**Comment by skoehnen** [comment]
On second look the url was already an array.

**Comment by lzehl** [comment]
Does this mean we can close the issue?

**Comment by lzehl** [comment]
Or to be more precise: is it still necessary that I integrate your pull request?

**Comment by skoehnen** [comment]
I think this is fine as is.
I will close this.
