### ISSUE TITLE
could we fix the "née" structurally for persons for the release?

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#463]
currently we integrate this into the string of the familyName (e.g., "Ruland (née Bradler)").
I would rather extract this into it's own property field (optional of course).

@apdavison @olinux @Peyman-N @aeidi89 what do you think?

**Comment by lzehl** [comment]
**Note:** I've used the property name "birthName" now which is a bit imprecise, since this may be applied to the family name, the given name, or the entire name. I stated in the instructions though that we mean the family name here. Feel free to suggest a different property name / different approach to handle name changes. In EBRAINS they have use cases for family name changes due to marriages, they have no use case yet for a given name change in the KG (which is also possible).

**Comment by lzehl** [comment]
@jcolomb how do you handle this in **jams**?

**Comment by lzehl** [comment]
Based on the discussion with @aeidi89 we suggest to use "alternateFamilyName" and "alternateGivenName".

**Comment by apdavison** [comment]
I agree with using "alternate...", since people change their names for many reasons.

**Comment by jcolomb** [comment]
We do not have talked about this in jams, I am not aware of anything in jatsxml. orcid uses "Also known as" which would be full name alternative.

**Comment by lzehl** [comment]
@jcolomb thanks for your feedback. ORCID matches roughly what schema.org is doing. I think we are then a bit more specific but close enough to running standards with "alternateFamilyName" and "alternateGivenName"

**Comment by jcolomb** [comment]
Wondering if "alternateName" would not be simpler ( imagine if someone change their family and given name (at different time), would you need to compute all different possibilities to get all the alternate names ?)

**Comment by lzehl** [comment]
Mh... @jcolomb I see your point, but keeping it together makes it difficult to track what changed and if for example a system should show the family name as "FAMILYNAME (aka ALTERNATEFAMILYNAME)" (which is wanted by users in EBRAINS)

**Comment by lzehl** [comment]
done with #468
