### ISSUE TITLE
CLEANUP leftovers: change Person properties

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#468]
change Person "alternateGivenName", "alternateFamilyName" to "alternateName"
@jcolomb I gave it more thought and I agree with your argument from #464

this reduces also property names across schemas (cf. https://github.com/HumanBrainProject/openMINDS_SANDS/issues/245)

**Comment by aeidi89** [comment]
I agree with this

**Comment by lzehl** [comment]
@olinux changed already by accident in v4. should be okay I hope
