### ISSUE TITLE
update / extend uniMINDS v2.0 documentation

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#47]
@UlrikeS91 : thanks for taking care of this :) task description:
The documentation of the uniMINDS v2.0 wiki needs to be updated and extended:
+ format of wiki/docu should match MINDS v1.0 docu
+ softwarecatalog, softwarecatalog options, and neuralactivity schemas need to be added

**Comment by UlrikeS91** [comment]
@lzehl: The v2 wiki is now updated and extended.

Some general comments: 
- I made the wiki similarly to the v1 wiki (as you wanted)
- I sorted the properties for each schema to following way:
     1. `@type` 
     2. `@id` 
     3. `name` (always required; name = alias, name, title, etc.)
     4. other required properties sorted alphabetically
     5. optional properties sorted alphabetically
- I applied this sorting logic also to the [v1 wiki](https://github.com/HumanBrainProject/openMINDS/wiki/v1:-MINDS)

Some open questions:
- the neuralactivity is v0.1.0/not released: Still keep it?
- required fields: as you suggested I, I orientated on v1 required fields, but this should be revised and updated
- Should this wiki be a 100% accurate reflection of what is in the KG right now? For example, for one property (don't remember which one exactly), the property was called "Method" and not Method/Paradigm. It still referred to the same, just an inconsistency in the KG. Should I correct this in the documentation or copy it exactly as is right now? 

Things missing: 
- adding references to existing JSON LDs (on "KG Metadata Archive")
- there are some "???" in the wiki that should probably be clarified
- someone else proof-reading the v2 wiki

**Comment by lzehl** [comment]
I'm closing this issue for now. We should at one point get back to the question if we want to redo/provide the implementation for the old models (MINDS and uniMINDS) as well, but this is currently of low priority.
