### ISSUE TITLE
CustomPropertySet add StringProperty/NumericalProperty to "dataLocation" types

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#478]
...to reduce the overhead of a user when he/she just wants to register a single property-value pair. @apdavison You think that makes sense?

**Comment by apdavison** [comment]
This won't work because StringProperty is supposed to be embedded.

**Comment by lzehl** [comment]
@apdavison of course... I know I overlooked something. Then it's just a bit on an overhead users have to handle.
