### ISSUE TITLE
add common metadata (@id) to KG Metadata Archive

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#48]
@UlrikeS91 : thanks for helping out with this!

 I've prepared a wiki page [KG Metadata Archive](https://github.com/HumanBrainProject/openMINDS/wiki/KG-Metadata-Archive) and pasted already some of the commonly used metadata in there.

If you want we can discuss what should go in there before you update the wiki. Just comment in this issue.

**Comment by lzehl** [comment]
@UlrikeS91 : I think the following ones should be easy:
+ license/Information
+ minds/Preparation
+ minds/Sex
+ minds/Species

Here are the ontology "supported" modalities (at the moment):
+ expression
+ genomics
+ cell culture
+ histology
+ morphology
+ cell morphology
+ transcriptomics
+ electrophysiology
+ cell population characterization
+ radiology
+ microscopy
+ physiology
+ anatomy
+ optical
+ cell counting
+ connectivity
+ spatial transcriptomics
+ expression characterization
+ epigenomics
+ behavioral (this one should be renamed to "behavior")
+ models

The minds/Format need to be discussed (current entries are not very well defined).
We should meet for that.

**Comment by UlrikeS91** [comment]
I added the `@id` for the MINDS v1 tables you added to the wiki except for minds/Files. This one should be discussed and go through a clean-up. 

I didn't notice your modality list, but I cross-checked them and apparently your list was the same as the one I had. Only additional one is "multimodal" and "behavioural" is called "behavioural assay" (which you renamed yourself in the KG). If it should still be renamed to "behaviour", let me know. Then I'll change it in the KG and in the wiki. 

I'll start working on uniMINDS common metadata next (but don't know when exactly).

**Comment by lzehl** [comment]
For "Formats2 I will go through the existing ones in the KG for preparing a clean up.

**Comment by lzehl** [comment]
can be closed. is solved differently for v3.0 (cf. controlledTerms)
