### ISSUE TITLE
role taxononmy: use CRO

### ISSUE THREAD

**Issue by jcolomb** [openMetadataInitiative/openMINDS_core#49]
just saw there is a  role.schema.json file (that was just updated).

I would encourage you to use the CRO (contribution role ontology) which is the follow up of the CrediT. http://www.obofoundry.org/ontology/cro.html, https://github.com/data2health/contributor-role-ontology

If something is missing, expanding the CRO would probably be better than recreating an independent system, I know some of the people involved and I think they would love some feedback/contributions.

**Comment by lzehl** [comment]
Hi! This is good feedback, thanks! The current role schema (in MINDS v1.0) is not further defined and used though. I will keep this issue open though for openMINDS v3.0.

@jcolomb : do you know if CRO is using datacite as basis? I was aiming to only cover roles defined by datacite.

**Comment by mellybelly** [comment]
We can create a subset tag for the datacite roles if you like. Please make a ticket and let us know your needs and also to get notified when it is done.

**Comment by mellybelly** [comment]
looks like you are needing contributor types here: https://support.datacite.org/docs/schema-optional-properties-v43 ?

**Comment by lzehl** [comment]
@mellybelly yes :) thank you! This is exactly what I was referring to. For v3 I was planning to support those ones.

**Comment by lzehl** [comment]
for further discussions see: https://github.com/HumanBrainProject/openMINDS_controlledTerms/issues/9
