### ISSUE TITLE
Linkage of affiliations to research products

### ISSUE THREAD

**Issue by apdavison** [openMetadataInitiative/openMINDS_core#500]
People may have many affiliations over their career, but for a given research product only a subset of the affiliations should apply. At the moment, we are using start dates and end dates of Affiliations to determine this indirectly (where we have this information, which is not often), but this is not satisfactory because people often publish articles and data some time after they have left a given position. 

We therefore need a way to indicate directly which affiliations should apply to a given research product. A couple of options come to mind: (1) introduce a PersonState schema. This has the additional advantage that it could handle changes of name, gender, e-mail address, etc; (2) in the "author" and "custodian" properties, use Affiliation instead of Person as the linked type.

**Comment by lzehl** [comment]
will be followed up on here #513
