### ISSUE TITLE
addressing needs of organizational structures

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#502]
# Currently in openMINDS:

LegalPerson:
+ Person (natural person; properties: affiliation, alternateName, associatedAccount, contactInformation, digitalIndentifier, familyName, **givenName**)
+ Organization (artificial person; properties: affiliation, digitalIdentifier, **fullName**, hasParent, homepage, shortName)

----
+ Consortium (no legal capacity; properties: contactInformation, **fullName**, homepage, shortName)
(LegalPerson -> Affiliation --> Consortium)
----
+ Affiliation (properties: **memberOf**, startDate, endDate)
(LegalPerson -> Affiliation --> Consortium | Organization)
----
-> embedded type
--> linked type
**required property**

# Suggestion for future (TBD):

Person
+ add name (make this required instead of givenName)
+ change associatedAccount to account
----
Organization
+ add type (controlledTerm: university, hospital, non-profit organization, company, ...?) or split up into distinct types?
+ add geographicalLocation (link to new schema)
----
Consortium
+ should they also get an affiliation?
----
Affiliation
+ may need a back link to ResearchProduct(Version) (related to #500)?

**Comment by tgbugs** [comment]
https://ror.org
http://rrid.site
https://scicrunch.org/resources/data/source/nlx_144509-1/search

**Comment by lzehl** [comment]
will be followed up on here https://github.com/openMetadataInitiative/openMINDS_core/issues/513
