### ISSUE TITLE
Set up GitHub Actions for CI

### ISSUE THREAD

**Issue by skoehnen** [openMetadataInitiative/openMINDS_core#52]
The HBP organisation now has access to Git Actions.

**Comment by skoehnen** [comment]
The workflow is now up and running, and I fixed the errors as far as I could.
I will need some feedback on my changes in <file> in PR #58

**Comment by xgui3783** [comment]
> The HBP organisation now has access to Git Actions.

shut the front door... it what now?

**Comment by lzehl** [comment]
@skoehnen feel free to close this issue if you see it solved.

**Comment by lzehl** [comment]
@skoehnen can we close this issue? If so, please go ahead and close it.

**Comment by skoehnen** [comment]
@lzehl I think we can close it.
But we should maybe revisit it in the future to see if this still covers our needs.
