### ISSUE TITLE
Handling of python code in this repository

### ISSUE THREAD

**Issue by skoehnen** [openMetadataInitiative/openMINDS_core#53]
How should we handle the mixing of python code and schemas in this repository.
The easiest solution would be to start a new repository and move all the python code there (which currently is only one file, but will probably be more in the future).

**Comment by jcolomb** [comment]
I think the cleanest way might be to create one parent repository where the python repo and the schema repos are both submodules. This would allow the possibility to add other submodules (R scripts doing the same, for instance) and keep the discussion in the sub-modules repositories. But I have no practical experience with this, there might well be something I do not think of.

**Comment by lzehl** [comment]
Done :) code is going to be in HumanBrainProject/compile_openMINDS which will have a submodule to openMINDS
Note: the name might change
