### ISSUE TITLE
Minor syntax issues

### ISSUE THREAD

**Issue by ieaasebo** [openMetadataInitiative/openMINDS_core#7]
Since I was already on it :)

model.schema.json
-line 35. Missing entry
subject.schema.json
-line 86. remove comma or add another entry to array
temporalSubjectInfo.schema.json
-line 40. remove comma or add another entry to array

**Comment by lzehl** [comment]
Keep collecting :) I'll try to fix all of them along the way :)

**Comment by skoehnen** [comment]
Should we maybe set up continuous testing for this repository?
Then those errors would pop up instantly.

**Comment by lzehl** [comment]
I think that's a great idea! Would you take care of it?

**Comment by skoehnen** [comment]
Is this still an open issue?

**Comment by lzehl** [comment]
I think we can close it. I think I corrected all, but we anyway need to rewrite the v3 schemas soon.
For this reason, I'll close the issue.
