### ISSUE TITLE
improvement of validator

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#70]
@skoehnen could you add a validator to v1.0 or generalize the existing validator from v3.0 so that it validates v1.0, and v3.0 (and v2.0 if it would exist)? I would prefer the latter option (one validator at the top level). 

Further we could make the validator (or validators) check more details of the implementations (which will be version dependent) that could help avoiding typical errors. I imagine something like: 
- general validation -> purely check for errors in JSON-Schema format in all versions
- specific validation -> check for content errors (e.g. `@type` pattern) in each version

What do you think? 

This doesn't have priority. Only take care of it when you have some time left or let me know if I should take over.

**Comment by lzehl** [comment]
@skoehnen & @olinux feel free to close this issue, I think it's a bit outdated with all the repo changes that happened...

**Comment by skoehnen** [comment]
Okay :+1:
Is closed.
