### ISSUE TITLE
person.schema: why not use datacite json schema directly

### ISSUE THREAD

**Issue by jcolomb** [openMetadataInitiative/openMINDS_core#72]
see https://github.com/datacite/schema/blob/master/source/json/kernel-4.3/datacite_4.3_schema.json

This may go around some discussion we had previously here #17 
As I understood, datacite compatibility is a major conceern here, right?

**Comment by lzehl** [comment]
Hi. Yes, in principle you are correct. We want to be compatible with other schemas as much as possible.
The datacite schema is though, less modular than we want it to be. I would prefer being compatible to elements of it, but keeping it close to the flexible design we want to have for the Knowledge Graph.

**Comment by lzehl** [comment]
I'm closing this issue. Further discussions can be made in issue #83
