### ISSUE TITLE
v3 schema-revision: researchProduct.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#73]
The `researchProduct.schema.json` will be used to group different versions of one research product (dataset, model or software).  
Note: this schema was previously documented as `product.schema.json`.  

According to the current documentation, this schema will have the following properties:
- **alias** [expects: free text, count: 1]
- **custodians**: [expects: person.schema.json|organization.schema.json, count: 1 - N]
- **otherContributions**: [expects: contribution.schema.json, count: 0 - N]
- **digitalIdentifier** [expects: digitalIdentifier.schema.json, count: 1]
- **homepage** [expects: string (format: uri), count: 0 - 1]
- **name** [expects: free text, count: 1]
- **summary** [expects: free text, count: 1]

**Comment by skoehnen** [comment]
@lzehl I just saw that you moved this from Implemented to Documented.
Is here more work necessary?

**Comment by lzehl** [comment]
Yes. Based on Feedback from @olinux this needs some changes. Please leave it in documented

**Comment by olinux** [comment]
Suggestion:
- Use this schema as an "abstract" schema and make individual schemas extending it for "dataset", "model" and "software" ("hasVersions" will be specified in the specific schemas to ensure that a dataset only contains datasetVersions, etc.)
- Change "contributors" to "contributions"
- Remove "type" since the individual schemas already make it explicit

**Comment by lzehl** [comment]
>     * Use this schema as an "abstract" schema and make individual schemas extending it for "dataset", "model" and "software" ("hasVersions" will be specified in the specific schemas to ensure that a dataset only contains datasetVersions, etc.)

Yes, as agreed in the discussions we had. @olinux Could you create the correspondingly missing schema-revision issues for dataset, model and software? And please check if the updated docu above would be correct for the abstract schema.

>     * Change "contributors" to "contributions"

This one should be discussed a bit more.

>     * Remove "type" since the individual schemas already make it explicit

I've updated the docu above correspondingly

**Comment by lzehl** [comment]
@olinux what about "individualContributions" or "contributingParties"? instead of "contributors"

1)  btw. in principle "funding" is also a contribution. should we keep it separate anyhow?
2) what about acknowledgements in this context? not only funders can be acknowledged
