### ISSUE TITLE
v3 schema-revision: datasetVersion.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#74]
The `datasetVersion.schema.json` will contain mainly bibliographical metadata on data structures originating from human or animal experiment or a simulation.
Note: in MINDS (v1), the related schema was defined as `dataset.schema.json`.  

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/datasetVersion"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **alias** [expects: free text, count: 1]
- **authors**: [expects: person.schema.json|organization.schema.json, count: 1 - N] 
- **availability** [expects: controlledTerm.schema.json, count: 1] 
- **custodians**: [expects: person.schema.json|organization.schema.json, count: 1 - N] 
- **otherContributions**: [expects: contribution.schema.json, count: 0 - N]
- **digitalIdentifier** [expects: digitalIdentifier.schema.json, count: 1]
- **documentation**: [expects: digitalIdentifier.schema.json, count: 1]
- **ethicsAssessment**: [expects: controlledTerm.schema.json, count: 1] (updated according to discussion below)
- **funding** [expects: funding.schema.json, count: 1 - N]
- **isNewVersionOf**: [expects: datasetVersion.schema.json, count: 0 - 1]
- **isSupplementTo**: [expects: datasetVersion.schema.json, count: 0 - N]
- **isVariantFormOf**: [expects: datasetVersion.schema.json, count: 0 - N]
- **homepage** [expects: string (format: uri), count: 0 - 1]
- **license** [expects: license.schema.json, count: 1]
- **modality** [expects: controlledTerm.schema.json, count: 1 - N] 
- **name** [expects: free text, count: 1]
- **relatedPublications**: [expects: digitalIdentifier.schema.json, count: 0 - N]
- **releaseDate** [expects: string (format: date), count: 1]
- **repository**: [expects: fileRepository.schema.json, count: 1]
- **studyTargets**: [expects: studyTarget.schema.json, count: 1]
- **summary** [expects: free text, count: 1]
- **type** [expects: controlledTerm.schema.json, count: 1 - N] 
- **versionIdentifier** [expects: free text, count: 1]
- **versionInnovations** [expects: free text, count: 1]

Note for controlledTerm.schema.json for...
- **availability** (`productAvailability`): expects JSON-LDs for `free`, `embargoed`, `exclusive login`, `restricted`, `closed`, +?
- **ethicsAssessment** (`ethicsAssessment`): expects JSON-LD for `EU compliant` and `not required`
- **modality** (`modality`): expects JSON-LDs for (cf. list on internal curation GitLab or ontology documentation)
- **type** (`datasetType`): expects JSON-LDs for `raw data`, `derived data` or `simulated data`

**Comment by UlrikeS91** [comment]
I would prefer `ethicsApproval` over `euEthicsCompliance`. The EU compliance is quite specific to what we are doing, we should rather capture the documentation directly (which is also often done in article publications). 

I'll implement the schema with `ethicsApproval` for now. We can change it later if anybody can make a good case against it :)

**Comment by UlrikeS91** [comment]
Question related to the `ethicsApproval`: How would datasets be handled that don't require an approval? Will there be an option to state exactly this since the property itself is required?

**Comment by UlrikeS91** [comment]
Question related to `isNewVersionOf`: Why would this allow 1 - N objects? Wouldn't it make more sense to only allow 1. This way the provenance would be more clear and straight-forwards. And since we have `isSupplementTo` and `isVarientFormOf`, there are many option to express additional relationships to other dataset versions.

**Comment by UlrikeS91** [comment]
Question related to `license`: Again why allow several (count: 1 - N)? This seems illogical. A dataset should be made available with one license. If a dataset would need several, then the dataset should rather be split up into several datasets as well.   

Additional side-note: If one dataset version has been published with a share-alike license type, the following new versions should be published with the same. This should be checked at some stage of the curation process. How does this apply to alternative versions and supplementing versions?

**Comment by UlrikeS91** [comment]
Question related to `modality`: Why only allow one modality?

**Comment by lzehl** [comment]
For your comments/questions for `ethicsApproval`:
1) GDPR sensitive data should not state the ethics authority because this gives a demographic context which should lead to the re-identification of data. The only reason why journals (and we) ask for ethics information is to officially state that they are compliant with the corresponding legislation of the service (journal, database, etc.). In our case the ethics approval and their compliance with EU legislation are performed by the EBRAINS ethics team which currently capture the required information for this elsewhere (and privately/not open for the public). Only relevant for our database is that it is EU compliant which could be handled with a general disclaimer in the KG ("The ethics approval of this dataset is compliant with EU law/legislation"). 
2) If a dataset did not need any ethical approval it should be explicitly stated. This could be handled over a corresponding option/menu/controlledTerm and lead to a corresponding disclaimer in the KG ("This dataset did not require an ethics assessment")

How about calling the property `ethicsAssessment` which leads to a `controlledTerm` (["EU compliant", "not required"])?
We should discuss this part with Will and Ida.

**Comment by lzehl** [comment]
For your comment on `isNewVersionOf` : agreed (this is a copy paste error)! I changed it to be count: 0 - 1.

For your comment on `license` : agreed (this is a copy paste error)! I changed it to be count: 1.

For your comment on `modality` : agreed (this is a copy paste error)! I changed it to be count: 1 - N.

**Comment by UlrikeS91** [comment]
> For your comments/questions for `ethicsApproval`:
> 
> 1. GDPR sensitive data should not state the ethics authority because this gives a demographic context which should lead to the re-identification of data. The only reason why journals (and we) ask for ethics information is to officially state that they are compliant with the corresponding legislation of the service (journal, database, etc.). In our case the ethics approval and their compliance with EU legislation are performed by the EBRAINS ethics team which currently capture the required information for this elsewhere (and privately/not open for the public). Only relevant for our database is that it is EU compliant which could be handled with a general disclaimer in the KG ("The ethics approval of this dataset is compliant with EU law/legislation").
> 2. If a dataset did not need any ethical approval it should be explicitly stated. This could be handled over a corresponding option/menu/controlledTerm and lead to a corresponding disclaimer in the KG ("This dataset did not require an ethics assessment")
> 
> How about calling the property `ethicsAssessment` which leads to a `controlledTerm` (["EU compliant", "not required"])?
> We should discuss this part with Will and Ida.

Thanks for the explanations. Everything sounds reasonable to me then :) I like `ethicsAssessment` and if nothings speaks against doing this, I think we should go for it.

**Comment by olinux** [comment]
Suggestions:
- change "contributors" to "contributions" (because it points to an intermediate object
- change "documentation" to DigitalIdentifier (URL, DOI, ISBN...)

**Comment by lzehl** [comment]
>     * change "contributors" to "contributions" (because it points to an intermediate object
Not sure yet if I like it. Let's discuss this later.

>     * change "documentation" to DigitalIdentifier (URL, DOI, ISBN...)
I agree (this was a left over and not corrected yet). Doc above is updated accordingly now.
