### ISSUE TITLE
v3 schema-revision: modelVersion.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#75]
The `modelVersion.schema.json` will contain mainly bibliographical metadata on data structures originating from a computational model.
Note: in uniMINDS (v2), the related schema was defined as `modelInstance.schema.json`.  

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/modelVersion"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **abstractionLevel** [expects: controlledTerm.schema.json, count: 1] 
- **alias** [expects: free text, count: 1]
- **authors**: [expects: person.schema.json|organization.schema.json, count: 0 - N] 
- **availability** [expects: controlledTerm.schema.json, count: 1] 
- **developers**: [expects: person.schema.json, count: 1 - N] 
- **otherContributions**: [expects: contribution.schema.json, count: 1 - N]
- **digitalIdentifier** [expects: digitalIdentifier.schema.json, count: 1]
- **documentation**: [expects: resource.schema.json, count: 1]
- **funding** [expects: funding.schema.json, count: 1 - N]
- **inputDataset**: [expects: datasetVersion.schema.json, count: 0 - N]
- **isNewVersionOf**: [expects: modelVersion.schema.json, count: 0 - N]
- **isSupplementTo**: [expects: modelVersion.schema.json, count: 0 - N]
- **isVariantFormOf**: [expects: modelVersion.schema.json, count: 0 - N]
- **homepage** [expects: string (format: uri), count: 0 - 1]
- **hostedBy** [expects: controlledTerm.schema.json, count: 1] 
- **license** [expects: license.schema.json, count: 1 - N]
- **modelFormat** [expects: mediaType.schema.json, count: 1] (see discussion below)
- **name** [expects: free text, count: 1]
- **outputDataset**: [expects: datasetVersion.schema.json, count: 0 - N]
- **relatedPublications**: [expects: resource.schema.json, count: 0 - N]
- **releaseDate** [expects: string (format: date), count: 1]
- **repository**: [expects: fileRepository.schema.json, count: 1]
- **studyTargets**: [expects: studyTarget.schema.json, count: 1]
- **scope** [expects: controlledTerm.schema.json, count: 1] 
- **summary** [expects: free text, count: 1]
- **versionIdentifier** [expects: free text, count: 1]
- **versionInnovations** [expects: free text, count: 1]

Note for controlledTerm.schema.json for...
- **abstractionLevel** (`modelAbstractionLevel`): expects JSON-LDs for (cf. uniMINDS entries?)
- **availability** (`productAvailability`): expects JSON-LDs for `free`, `embargoed`, `exclusive login`, `restricted`, `closed`, +?
- **format** (`modelFormat`): expects JSON-LDs for (cf. uniMINDS entries?) OR (`programmingLanguage`) ??
- **hostedBy** (`repositoryHost`): expects JSON-LDs for `EBRAINS`, `custom`, `GitHub`, `GitLab`, `openNeuro`, +? 
- **scope** (`modelScope`): expects JSON-LDs for (cf. uniMINDS entries?)

**Comment by lzehl** [comment]
@apdavison & @bweyers could the property `format` be also handled as `programmingLanguage`?  
I've compared the previous entries in the KG between those and they overlap quite a bit. 

If `programmingLanguage` nor `format` is quite fitting the content of both joint together could we find a corresponding term that describes the values of both?

**Comment by apdavison** [comment]
`programmingLanguage` doesn't work for models, because not all models are expressed as source code. However, it seems like a natural term to use for software, where "format" would be much more vague in its meaning.

**Comment by lzehl** [comment]
@apdavison what do you suggest now? I'm not very happy about handling this separately since most values are the same...
What about naming the poperties differently in modelVersion and softwareVersion (as it is right now) but both point to the same controlledTerms?

**Comment by apdavison** [comment]
Note that the values used for model format are likely to be modified during the migration to openMINDS. For some cases the value will still be a single programming language, but in general we will be adding additional information. My plan was to  use media type / content type identifiers for this.

Also note that `programmingLanguage` should allow a list (since many pieces of software are implemented using more than one language) whereas `format` should not.

**Comment by lzehl** [comment]
okay, thanks for explaining a bit more around this. Here a summary of what I will note down (in the docus of the corresponding schema issues):

- within **modelVersion** keep property `modelformat` with count 1 and links possible to mediaTypes
- within **softwareVersion** keep property `programmingLanguage` with count 1 - N and links possible to controlledTerms (for programming languages)

**Comment by olinux** [comment]
Suggestions:
- Change "contributors" to "contributions"
- Change "documentation" to "digital identifier"
- Change "relatedPublication" to "digital identifier"
