### ISSUE TITLE
v3 schema-revision: softwareVersion.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#76]
The `softwareVersion.schema.json` will contain mainly bibliographical metadata on data structures building a software tool.
Note: in uniMINDS (v2), the related schema was defined as `software.schema.json`.  

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/softwareVersion"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **alias** [expects: free text, count: 1]
- **authors**: [expects: person.schema.json|organization.schema.json, count: 0 - N] 
- **applicationCategory**: [expects: controlledTerm.schema.json, count: 1 - N] 
- **availability** [expects: controlledTerm.schema.json, count: 1] 
- **otherContributions**: [expects: contribution.schema.json, count: 0 - N]
- **copyright**: [expects: copyright.schema.json, count: 0 - 1]
- **developers**: [expects: person.schema.json, count: 1 - N] 
- **device**: [expects: controlledTerm.schema.json, count: 1 - N] 
- **digitalIdentifier** [expects: digitalIdentifier.schema.json, count: 1]
- **documentation**: [expects: digitalIdentifier.schema.json, count: 1]
- **funding** [expects: funding.schema.json, count: 1 - N]
- **inputFormat**: [expects: contentType.schema.json, count: 1 - N]
- **isNewVersionOf**: [expects: softwareVersion.schema.json, count: 0 - N]
- **isSupplementTo**: [expects: softwareVersion.schema.json, count: 0 - N]
- **isVariantFormOf**: [expects: softwareVersion.schema.json, count: 0 - N]
- **homepage** [expects: string (format: uri), count: 0 - 1]
- **hostedBy** [expects: controlledTerm.schema.json, count: 1 - N] 
- **language**: [expects: controlledTerm.schema.json, count: 1 - N] 
- **license** [expects: license.schema.json, count: 1 - N]
- **name** [expects: free text, count: 1]
- **operatingSystem**: [expects: controlledTerm.schema.json, count: 1 - N] 
- **outputFormat**: [expects: contentType.schema.json, count: 1 - N]
- **programmingLanguage**: [expects: controlledTerm.schema.json, count: 1 - N] 
- **relatedPublications**: [expects: digitalIdentifier.schema.json, count: 0 - N]
- **releaseDate** [expects: string (format: date), count: 1]
- **repository**: [expects: fileRepository.schema.json, count: 1 - N]
- **softwareFeature** [expects:  softwareFeature.schema.json, count: 1 - N]
- **softwareRequirement** [expects: free text, count: 1]
- **summary** [expects: free text, count: 1]
- **versionIdentifier** [expects: free text, count: 1]
- **versionInnovations** [expects: free text, count: 1]

Note for controlledTerm.schema.json for...
- **applicationCategory** (`softwareApplicationCategory`): expects JSON-LDs for (cf. uniMINDS entries?)
- **availability** (`productAvailability`): expects JSON-LDs for `free`, `embargoed`, `exclusive login`, `restricted`, `closed`, +?
- **device** (`operatingDevice`): expects JSON-LDs for (cf. uniMINDS entries?)
- **language** (`language`): expects JSON-LDs for (cf. uniMINDS entries?)
- **hostedBy** (`repositoryHost`): expects JSON-LDs for `EBRAINS`, `custom`, `GitHub`, `GitLab`, `openNeuro`, +? 
- **operatingSystem** (`operatingSystem`): expects JSON-LDs for (cf. uniMINDS entries?)
- **programmingLanguage** (`programmingLanguage`): expects JSON-LDs for (cf. uniMINDS entries?)

**Comment by lzehl** [comment]
@bweyers could you please support us here and double check that everything you need for the software curation is in place considering this schema?

**Comment by bweyers** [comment]
@lzehl I added Jan (@jagru20) to the discussion via email such that he can also have a look. In a first overview it looks fine! I guess Jan will also give feedback after checking it together with our meta data curators.

**Comment by lzehl** [comment]
@bweyers perfect, thanks! @jagru20 looking forward to your comments :slightly_smiling_face:

**Comment by jagru20** [comment]
Hi @lzehl, thanks for working on this.

I have just a few comments/questions: 

1. In the schema we currently use, we have the additional field _description_ which is not listed above. _description_ is sometimes confused with _summary_. _summary_ should be one sentence, whereas _description_ is supposed to be more comprehensive. To us, _description_ is the more important one.
1. We also use the properties _keywords_, _screenshots_ and _icon_ for which I do not find an equivalent above. Screenshots and icons are provided as URLs, pointing to the picture files.
1. Do you make a distinction between copyright holder and year?

**Comment by xgui3783** [comment]
Hi, can you assign me to this issue?

**Comment by skoehnen** [comment]
> Hi, can you assign me to this issue?

Done

**Comment by lzehl** [comment]
@jagru20 thanks for your comments/questions. Here my feedback 

**to 1)** note that `summary` is not generally assumed to be only one sentence. According to the data descriptor and how this is going to be displayed in the KG Search this property should be a free text with maximum length of (170 words maximum, no references).  But I do not have a strong opinion on the name of this property except that it should be consistent across all research products (dataset, model, software). I'm okay with: `description`, `summary`, `abstract`, `shortDescription`. Could you make an issue for this (concerns #74 #75 #76)?

**to 2)** 
  - `keywords` was ruled out in one of the discussions about the openMINDS v3 version since the new model/schema give enough (more generalized) options that can be used as keywords in the KG Search landing pages. I would like to test this more standardized way of defining keywords than just user defined free text, but we can reverse this decision if we see we need this option.
  - `screenshots` and `icon` should be defined on the file level (at least this was the last discussion I had with Oli). Defining special role of certain files. But I think I forgot to put this option into the fileInstance.schema.json (thanks for the reminder!). Would that work for you?

**Comment by xgui3783** [comment]
Some questions that came up when putting together the PR:

- `hostedBy` and `repository`: should they be [1-N] in the event that the same version of the software can exist on separate mirrors (github & gitlab) ? Or is the idea that in this case, there should be two separate softwareVersions ?

**Comment by apdavison** [comment]
@xgui3783 I think they should be [1-N] for the reason you suggest.

**Comment by jagru20** [comment]
@lzehl 

1) This is fine for us. Although some of the descriptions contain more than 170 words, this is not the majority. Regarding the naming of this property: From our side,  `summary` is fine. We can just use this instead of splitting it up into `summary` and `description`. I did not mean to question the naming either. 

2) 

> screenshots and icon should be defined on the file level (at least this was the last discussion I had with Oli). Defining special role of certain files. But I think I forgot to put this option into the fileInstance.schema.json (thanks for the reminder!). Would that work for you?

I am not sure about this. As we do not integrate files into the KG but rather references and links to the repos or other places where the software itself is published, we cannot easily mark certain files as special ones. This is why we used the links to the files in the developer's repos so far. But if this is too complicated to integrate into the schema or would cause inconsistencies, we can also discuss omitting the `screenshots `and `icons.`

**Comment by lzehl** [comment]
@jagru20 with "files" I mean the metadata representation of them (cf. #81 ). In principle it's just a pointer to the physical file (in case of `screenshots` and `icons` there must also be a physical file somewhere, correct? Just not necessarily on CSCS)

NOTE: All file related schemas (fileRepository #79 , fileBundle #80 , fileInstance #81 ) can now also be used independent of CSCS.

**Comment by lzehl** [comment]
@jagru20 for point 1: would you like to capture though a one sentence description/summary for software besides a "normal" abstract (independent of the maximum word count which can still be discussed)

**Comment by jagru20** [comment]
> @jagru20 with "files" I mean the metadata representation of them (cf. #81 ). In principle it's just a pointer to the physical file (in case of `screenshots` and `icons` there must also be a physical file somewhere, correct? Just not necessarily on CSCS)

Ok I think I understand this now. That should work. 

>@jagru20 for point 1: would you like to capture though a one sentence description/summary for software besides a "normal" abstract (independent of the maximum word count which can still be discussed)

In short: I do not think, this is necessary. 
In long: As far as I understood, the distinction between`description` and `summary` as used in the software curation so far was intended primarily to provide a possibility for thorough descriptions without a word limit for interested users, respectively one sentence, that summarizes this description for those in a hurry. To me, a single 170-word description seems to be a fair compromise between these two and keeps the schema clear-cut.

**Comment by lzehl** [comment]
@jagru20 thanks for your feedback on this. So no changes are necessary in the documentation of the schema above? 
(besides the one suggested by @xgui3783)

**Comment by lzehl** [comment]
@xgui3783 & @apdavison I've updated the count for "hostedBy" and "repository" to "count: 1 - N".
I have a question though: how do such distributed mirrors work with digitalIdentifiers (such as DOI or RR ID)?

**Comment by apdavison** [comment]
@lzehl I'm not sure I understand the question about digital identifiers

**Comment by lzehl** [comment]
Sorry, I should have explained it better: a digital identifiers should point exactly to one physical representation of the data to ensure that the correct version is referenced / used, correct? How does this work with multiple repositories distributed over multiple hosts? Who guarantees the maintenance of the mirrors in such cases (so that they get not out of sync)? How should the user know which of the distributions is the one that actually is always maintained? 

Would it not be better to declare them explicitly as `otherDistributions` or something like this?

**Comment by xgui3783** [comment]
My 2c:

> a digital identifiers should point exactly to one physical representation of the data to ensure that the correct version is referenced / used, correct? 

yes. But whether the doi can support displaying multiple repositories, is another issue (doi for example, sets up a redirect. Do we prefer one repository over another?)

> Who guarantees the maintenance of the mirrors in such cases (so that they get not out of sync)?

In principle, if the repository points at a hash or a tagged release, and if they are setup to be in sync, they should never need to be updated. If changes are made, a new release/ softwareVersion should be created

> How should the user know which of the distributions is the one that actually is always maintained?

The user/developer should refer to the unique identifier of the software (not the unique identifier of the softwareVersion). Then, they can:

- retrieve all versions, and select one that is suitable or
- retrieve the desired version directly using versionIdentifer, if known

An analogy may be, for example, numpy:

unique software identifer (in this case, software name): `numpy`
softwareVersions: <https://pypi.org/project/numpy/#history>

- 1.19.2
- 1.19.1
... etc

**Comment by apdavison** [comment]
> a digital identifiers should point exactly to one physical representation of the data

I don't think that's true. Generally they point to a metadata page, and that page may or may not have links to the actual data (think DOIs, which point to a page on a journal website, not directly to the PDF, and that page may have the article in HTML, or may just have the abstract, depending on whether your university has a subscription to that journal. Also in that scenario, the HTML and PDF are two different representations with a single DOI.)

As for ensuring that different mirrors are in sync, I agree we will need some automated way of checking that. Although if they are both git repositories, then git itself guarantees that two clones/forks with the same hash are identical.

**Comment by lzehl** [comment]
Sounds logical to me. Thanks for explaining a bit more.

**Comment by jagru20** [comment]
> @jagru20 thanks for your feedback on this. So no changes are necessary in the documentation of the schema above?

Yes, there are no changes needed from our side. Is copyright.schema.json already defined somewhere? I am not able to find it...

**Comment by lzehl** [comment]
no not yet... I'm not keeping up with the speed of you guys. I'll define copyright.schema.json next :slightly_smiling_face:

**Comment by lzehl** [comment]
from @skoehnen the current schema implementation is missing a description (#106).

**Comment by lzehl** [comment]
@jagru20 could you have a look at the schema and add the missing description?

**Comment by jagru20** [comment]
Yes

**Comment by olinux** [comment]
Suggestions:
- Renaming "contributors" to "contributions" due to link to intermediate object
- Changing "documentation" and "relatedPublications" to DigitalIdentifier (representing URL, DOI, ISBN...)
- "isNewVersionOf", "isSupplementTo", "isVariantFormOf" should be "SoftwareVersion" not "ModelVersion"
- "inputFormat" and "outputFormat" are now "ContentType"

**Comment by lzehl** [comment]
> * Renaming "contributors" to "contributions" due to link to intermediate object

This one should be discussed a bit more.

> * Changing "documentation" and "relatedPublications" to DigitalIdentifier (representing URL, DOI, ISBN...)

Yes, I did not change this yet. I've updated the doc above accordingly.

> * "isNewVersionOf", "isSupplementTo", "isVariantFormOf" should be "SoftwareVersion" not "ModelVersion"

Yes, this is an error. I've updated the doc above accordingly.

> * "inputFormat" and "outputFormat" are now "ContentType"

Yes, I did not change this yet. I've updated the doc above accordingly.
