### ISSUE TITLE
v3 schema-revision: project.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#77]
The `project.schema.json` will be used to group different research products or their versions.  

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/project"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **alias** [expects: free text, count: 1]
- **hasResearchProducts**: [expects: researchProduct|datasetVersion|modelVersion|softwareVersion.schema.json, count: 1 - N]
- **homepage** [expects: string (format: uri), count: 0 - 1]
- **name** [expects: free text, count: 1]
- **description** [expects: free text, count: 1]

**Comment by olinux** [comment]
Suggestion:
- change "hasResearchProducts" to dataset|software|model|datasetVersion|modelVersion|softwareVersion.schema.json due to the split of the research products

**Comment by lzehl** [comment]
Did we not say that we should remove this property here and make the connection to the project in the individual research products ("isPartOf" or "belongsToProject", I prefer the first)? But maybe that's what you mean :sweat_smile:

**Comment by UlrikeS91** [comment]
> Did we not say that we should remove this property here and make the connection to the project in the individual research products ("isPartOf" or "belongsToProject", I prefer the first)? But maybe that's what you mean 😅

Even if @olinux didn't mean that, I would agree with you @lzehl. I would also prefer to add the property `isPartOf` to each of those research products :)
