### ISSUE TITLE
v3 schema-revision: controlledTerm.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#78]
The `controlledTerm.schema.json` will be valid for all controlled terms that are going to be used in the EBRAINS KG.  
Note: The actual controlled terms (JSON-LDs) for the KG will be created and maintained by the EBRAINS Curation Service in a different GitHub repository (coming soon). A user will be able to reference to the defined controlled terms on this GitHub by using their corresponding `@id`.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/controlledTerm"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **name** [expects: free text, count: 1]
- **relatedOntology** [expects: string (format: uri), count: 0 - 1]

**Comment by UlrikeS91** [comment]
also related to https://github.com/HumanBrainProject/SANDS/issues/41

**Comment by UlrikeS91** [comment]
For `relatedOntology`: I will do `"format": "iri"`. 

We have gone back and forth between the 2, but concluded (following an ontology meeting with @tgbugs) to use IRI. This decision was communicated on a different SANDS issue (https://github.com/HumanBrainProject/SANDS/issues/44). The one linked above says to use URI (which was stated on the same day as in issue 44, but shortly before). All `relatedOntology` properties for SANDS define format as IRI.

**Comment by lzehl** [comment]
@skoehnen or @UlrikeS91 could you check if the format can contain a oneOf option and lead to both (iri and uri)?  
I would prefer this for all web links instead of going back and forth...

**Comment by lzehl** [comment]
@UlrikeS91 controlledTerms does not belong in products, but should be placed on the main level. 
Parallel to the definitions.json I would suggest.

**Comment by UlrikeS91** [comment]
> @skoehnen or @UlrikeS91 could you check if the format can contain a oneOf option and lead to both (iri and uri)?
> I would prefer this for all web links instead of going back and forth...

Why not the opposite way around? 
As:

    "relatedOntology": {
      "type": "string",
      "description": "Identifier (IRI) to related ontological term.",
      "oneOf": [
        {"format": "iri"},
        {"format": "uri"}
        ]
     }

@skoehnen, What do you think?

**Comment by UlrikeS91** [comment]
> @UlrikeS91 controlledTerms does not belong in products, but should be placed on the main level.
> Parallel to the definitions.json I would suggest.

Wasn't sure where to put it ;) I'll move it when I make the new PR to fix the uri/iri thing once we found a conclusion for it.

**Comment by skoehnen** [comment]
> > @skoehnen or @UlrikeS91 could you check if the format can contain a oneOf option and lead to both (iri and uri)?
> > I would prefer this for all web links instead of going back and forth...
> 
> Why not the opposite way around?
> As:
> 
> ```
> "relatedOntology": {
>   "type": "string",
>   "description": "Identifier (IRI) to related ontological term.",
>   "oneOf": [
>     {"format": "iri"},
>     {"format": "uri"}
>     ]
>  }
> ```
> 
> @skoehnen, What do you think?

I think this is unnecessary because IRI is an extension of URI, which means that every possible URI is also an IRI, but not the other way around.
So if we set it to IRI we cover all URI and also support possible "URI" with Unicode symbols.

**Comment by lzehl** [comment]
@skoehnen if this is the case, use IRI. Thanks for checking this, that's certainly not my expertise.

**Comment by lzehl** [comment]
Based on a discussion I had with @olinux this schema needs slight changes and will need some new schemas that inherit the content of a the general controlledTerm.schema.json.

The idea overall structure of a controlledTerm is given in the conceptual schema controlledTerm.schema.json. The specific `@type` of the controlledTerm is then defined in controlledTerm-subschemas (e.g., biologicalSex.schema.json).

For this the controlledTerm.schema.json should be placed in a subdirectory called `controlledTerms/` and it's schema changed to:
```json
{
  "$id": "https://openminds.ebrains.eu/core/ControlledTerm.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "description": "Schema to define controlled terms which can be linked to ontology terms.",
  "type": "object",
  "required": [
    "@type",
    "@id",
    "name"
  ],
  "properties": {
    "@id": {
      "type": "string",
      "description": "Metadata node identifier."
    },
    "name": {
      "type": "string",
      "description": "Controlled term originating from a defined terminology."
    },
    "relatedOntology": {
      "type": "string",
      "description": "Identifier (IRI) to related ontological term.",
      "format": "iri"
    }
  }
}
```

A specific controlledTerm-subschema would then look like this (example `biologicalSex`):
```json
{
  "$id": "https://openminds.ebrains.eu/core/ControlledTerm/BiologicalSex.schema.json",
  "$schema": "http://json-schema.org/draft-07/schema#",
  "allOf": [
    {
      "$ref": "https://raw.githubusercontent.com/HumanBrainProject/openMINDS/master/v3.0/definitions.json#definitions/ControlledTerm"
    },
    {
      "properties": {
        "@type": {
          "type": "string",
          "const": "https://openminds.ebrains.eu/core/ControlledTerm/BiologicalSex"
        }
      }
    }
  ]
}
```

**Comment by lzehl** [comment]
@olinux could you check if the above comment is correct?

**Comment by UlrikeS91** [comment]
Is this related to your comment in https://github.com/HumanBrainProject/SANDS/pull/87? Does that mean that SANDS will also get a subfolder  SANDS/controlledTerms/ with schemas for each of the specific controlledTerm-subsechemas (e.g. laterality, unit and such)?

**Comment by lzehl** [comment]
no. I suggest to collect all controlledTerm-subsechemas in openMINDS only

**Comment by lzehl** [comment]
But for the definitions we can get more specific in both cases SANDS and openMINDS.
Meaning the $ref can point to the subschema directly (e.g. ...ControlledTerm/BiologicalSex)
