### ISSUE TITLE
v3 schema-revision: fileBundle.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#80]
The `fileBundle.schema.json` will be used to group files of a research product either due to their hierarchical storage organization (folder in which files are located) or conceptually across the storage hierarchy (files across folders that contain the data of, e.g., the same modality).
Note: For some repository hosts (e.g. EBRAINS) the hierarchical structure of file bundles can be detected semi-automatically within the KG system.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/fileBundle"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **contentType** [expects: contentType.schema.json, count: 0 - 1]
- **groupedBy** [expects: controlledTerm.schema.json, count: 0 - 1] (this property has to be added "manually" in all cases)
- **hash** [expects: hash.schema.json, count: 1] (this schema has to be added "manually" if KG does not auto. detected the file)
- **isPartOf** [expects: fileRepository|fileBundle.schema.json, count: 1] 
- **name** [expects: free text, count: 1]
- **resourceLocator** [expects: string (format: uri), count: 0 - 1]
- **storageSize** [expects: quantity.schema.json, count: 1]

Note for controlledTerm.schema.json for...
- **groupedBy** (`fileBundleGrouping`): expects JSON-LDs for `subject`, `modality`, `technique`, `task`, +?

**Comment by skoehnen** [comment]
> * **groupedBy** [expects: controlledTerm.schema.json, count: 0 - 1] (this property has to be added "manually" in all cases)

What do you mean with adding manually in this case?
The different terms?

**Comment by skoehnen** [comment]
What is the difference between `groupedBy` and `isPartOf`?

**Comment by lzehl** [comment]
`groupedBy` is used to tell what connects the `fileInstance`s linked in this `fileBundle`
This property can never be detected automatically, because the system couldn't know the grouping idea on it's own (maybe semi-automatic by the user is possible in case a certain pattern was used)

`isPartOf` just tells you the connection to the `fileRepository` or, in case it is a substructure, to another `fileBundle`

**Comment by skoehnen** [comment]
> `groupedBy` is used to tell what connects the `fileInstance`s linked in this `fileBundle`
> This property can never be detected automatically, because the system couldn't know the grouping idea on it's own (maybe semi-automatic by the user is possible in case a certain pattern was used)
> 
> `isPartOf` just tells you the connection to the `fileRepository` or, in case it is a substructure, to another `fileBundle`

Ah thanks, now I understand this a bit better.

Do you have a suggestion for the description? 🤔

**Comment by lzehl** [comment]
My suggestion:
**groupedBy** `"description": "Concept which was used to group the file instances into this file bundle"`
**isPartOf** `"description": "Link to file repository or bundle to which all file instances within this file bundle belong to"`

For the latter, conceptual file bundles that group file instances across physical file bundles should in most cases directly point to the file repository.

**Comment by lzehl** [comment]
TODO: change mediaType to contentType
