### ISSUE TITLE
v3 schema-revision: organization.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#84]
The `organization.schema.json` will be used to identify organizations that were involved in producing the research products or their versions.  
Note: funding is handled separately. 

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/contribution"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **digitalIdentifier**: [expects: digitalIdentifier.schema.json, count: 0 - 1]
- **homepage**: [expects: string (format: uri), count: 0 - 1]
- **name**: [expects: string (free text), count: 1]
- **parentOrganization**: [expects: organization.schema.json, count: 0 - N] (added because of comment below)

**Comment by apdavison** [comment]
What about adding a `parent` field? For example, my institute is the Paris-Saclay Institute of Neuroscience, it has two parent organisations: the CNRS and the Université Paris-Saclay. Any of these three might be interested in seeing how many datasets they have shared through EBRAINS.

**Comment by lzehl** [comment]
Agreed. I'll add it to the properties. 

@apdavison what about renaming "name" into "legalName" ? Do you think that is necessary?

**Comment by apdavison** [comment]
> what about renaming "name" into "legalName" ? Do you think that is necessary?

no, I don't think so
