### ISSUE TITLE
v3 schema-revision: quantitativeValue.schema.json

### ISSUE THREAD

**Issue by lzehl** [openMetadataInitiative/openMINDS_core#99]
The `quantitativeValue.schema.json` will be used to define a value (integer and/or float) with a unit.

According to the current documentation, this schema will have the following properties:
- **`@type`** [expects: constant (`"https://openminds.ebrains.eu/core/quantitativeValue"`), count: 1]
- **`@id`** [expects: free text, count: 1]
- **unit** [expects: controlledTerm.schema.json, count: 0 - 1]
- **value** [expects: number, count: 0 - 1] (required if minValue&maxValue is not given)
- **minValue** [expects: number, count: 0 - 1] (required if value is not given)
- **maxValue** [expects: number, count: 0 - 1] (required if value is not given)

Note for controlledTerm.schema.json for...
- **unit** (`unitTextAndCode`): expects JSON-LDs for `mm`, `µm`, `g`, + ?

**Comment by apdavison** [comment]
I suggest using a schema compatible with https://schema.org/QuantitativeValue

i.e. allow both unitText and unitCode, and allow ranges, specifying minValue and maxValue instead of value

Here is a list of some URIs for unitCode we're using already in Tier 3 curation: https://github.com/HumanBrainProject/fairgraph/blob/master/fairgraph/commons.py#L412

also, shouldn't **value** be `count: 1`?

**Comment by lzehl** [comment]
value should be count 1, yes that was a typo.

**Comment by lzehl** [comment]
@apdavison can the unitCode be understood as an ontology definition? Because then unitText and unitCode are covered in the controlledTerm.schema. I would like to keep the controlled parts separate from other schemas, makes maintenance easier. We might need to rethink the property "relatedOntology" in controlledTerm.schema.json and rename it to e.g., "source" which would allow also for defined terminology (which is not yet covered in an ontology).

As for minValue and maxValue, this was intended to be specifically stated as properties (e.g. ageMin, ageMax), but we could cover it within here as well which would reduce the value related properties of other schemas (for min and max). What I do not like about this, is that min and max value have to be of the same unit then which is in some cases not really nice (when visualized). I suggest we try it out and see if it's convenient and intuitive enough for users. For "value", "minValue", and "maxValue" the count needs to be then 0 - 1, because either "value" has to be there or "minValue" and "maxValue" has to be there. How this can be handled in json-schema I need to look up.

**Comment by UlrikeS91** [comment]
Discussion during meeting with @lzehl: `unit` should have count = 1. 

Additional suggestion: Split schema into two. 

1) quanitativeValue.schema.json with `unit` (count: 1), `value` (count: 1) and `uncertainty` (array of 2 numbers; count 0 - 1).
2) quanitativeValueRange.schema.json with `minValue` (expects: quanitativeValue; count: 1) and `maxValue` (expects: quanitativeValue; count: 1)
